drop table account if exists
drop table application if exists
drop table application_connection if exists
drop table attachment if exists
drop table client if exists
drop table comments if exists
drop table dashboard if exists
drop table email if exists
drop table emailList if exists
drop table emailSubscribe if exists
drop table gadget if exists
drop table gadget_properties if exists
drop table geoPoint if exists
drop table geoPoint_folder if exists
drop table geoPoint_type if exists
drop table group_permission if exists
drop table groups if exists
drop table groups_permission if exists
drop table hash_tags if exists
drop table hash_tags_hits if exists
drop table notification if exists
drop table permission if exists
drop table poll if exists
drop table poll_folder if exists
drop table poll_result if exists
drop table project if exists
drop table project_geoPoint if exists
drop table project_group if exists
drop table project_locations if exists
drop table question_category if exists
drop table question_category_questions if exists
drop table question_collection if exists
drop table question_dependence_survey if exists
drop table question_relations if exists
drop table questions if exists
drop table questions_answers if exists
drop table questions_dependencies if exists
drop table questions_pattern if exists
drop table social_account if exists
drop table survey_folder if exists
drop table survey_format if exists
drop table survey_group if exists
drop table survey_group_format if exists
drop table survey_group_project if exists
drop table survey_pagination if exists
drop table survey_result if exists
drop table survey_section if exists
drop table survey_section_questions if exists
drop table surveys if exists
drop table tweetPoll if exists
drop table tweetPoll_Folder if exists
drop table tweetPoll_save_published_status if exists
drop table tweetpoll_hashtags if exists
drop table tweetpoll_result if exists
drop table tweetpoll_switch if exists
drop table userAccount if exists
drop table userAccount_followers if exists
drop table userAccount_permission if exists
drop table userAccount_project if exists