INSERT INTO permission VALUES
(1, 'ENCUESTAME_ADMIN', 'ENCUESTAME_ADMIN'),
(2, 'ENCUESTAME_OWNER', 'ENCUESTAME_OWNER'),
(3, 'ENCUESTAME_PUBLISHER', 'ENCUESTAME_PUBLISHER'),
(4, 'ENCUESTAME_EDITOR', 'ENCUESTAME_EDITOR'),
(5, 'ENCUESTAME_USER', 'ENCUESTAME_USER');