<div class="tweetPollWrapper">
    <h1>Create TweetPoll</h1>
    <div dojoType="dijit.form.Form" id="tableForm">
        <div class="text" style="margin-top: 20px;">
            <div class="questionTitle" style="font-weight: bold;">Question</div>
            <div dojoType="dijit.form.Textarea"></div>
        </div>
        <div class="seccondSection" style="margin: 0 9%;">
            <div class="answers" style="float: left;">
                <div dojoType="encuestame.org.core.commons.tweetPoll.Answers"></div>
            </div>
            <div class="hashTags" style="float: right;">
                <div dojoType="encuestame.org.core.commons.tweetPoll.HashTags"></div>
            </div>
        </div>
    </div>
</div>