<div class="listItemTweet" dojoAttachEvent="onclick:_onClickItem">
   <div class="rightPanel">
        <div class="votesTitle">
            Votes
        </div>
        <div class="votesCount">
            0/${data.limitVotes}
        </div>
        <div class="rating">
            <div dojoType="dojox.form.Rating" numStars="5" value="2"></div>
        </div>
   </div>
   <div style="font-size: 130%; color: #70798C; font-weight: bold;">
    <span class="emptyFavourite" dojoAttachPoint="_favourite" dojoAttachEvent="onclick:_setFavourite">    </span>
        ${data.questionBean.questionName}
   </div>
   <div style="font-size: 80%; font-weight: bold;">
        <a href="${data.tweetUrl}" target="_blank">${data.tweetUrl}</a>
  </div>
  <div class="hashTags" style="padding: 2px;">
        <span class="tag">Tag 1</span>
        <span class="tag">Tag 2</span>
        <span class="tag">Tag 3</span>
        <span class="tag">Tag 4</span>
  </div>
  <div class="optionItem">
        <div style="float: left; width: 150px; font-size: 130%; font-weight: bold; color: green;">
            OPEN
        </div>
        <div style="float: left; width: 150px;">

        </div>
  </div>

</div>