<span>
    <a href="#" dojoAttachEvent="onclick:_open">Profile</a>
    <div class="profilePanel" dojoAttachPoint="_profileBox">
        <ul>
            <li><a href="${contextPath}/settings/configuration.jspx">Configuration</a></li>
            <li><a href="${contextPath}/settings/social.jspx">Social Accounts</a></li>
            <li><a href="${contextPath}/help">Help</a></li>
            <li>
              <a href="${contextPath}/user/logout">Log out</a>
            </li>
          </ul>
    </div>
</span>
