
ALTER TABLE ONLY public.survey_group_project DROP CONSTRAINT fkfd028d34b75f3482;
ALTER TABLE ONLY public.survey_group_project DROP CONSTRAINT fkfd028d3484536452;
ALTER TABLE ONLY public.useraccount_project DROP CONSTRAINT fkfbc45bbc84536452;
ALTER TABLE ONLY public.useraccount_project DROP CONSTRAINT fkfbc45bbc5f77a117;
ALTER TABLE ONLY public.tweetpoll_hashtags DROP CONSTRAINT fkf8c717d6da98ffe1;
ALTER TABLE ONLY public.tweetpoll_hashtags DROP CONSTRAINT fkf8c717d6286705d7;
ALTER TABLE ONLY public.geopoint_folder DROP CONSTRAINT fkf4a1d3ee6ef241e9;
ALTER TABLE ONLY public.geopoint_folder DROP CONSTRAINT fkf4a1d3ee6e4ed46d;
ALTER TABLE ONLY public.geopoint_folder DROP CONSTRAINT fkf4a1d3ee2b2a6ab4;
ALTER TABLE ONLY public.project DROP CONSTRAINT fked904b19514c1986;
ALTER TABLE ONLY public.project DROP CONSTRAINT fked904b194075e3fd;
ALTER TABLE ONLY public.comments DROP CONSTRAINT fkdc17ddf4f44558e9;
ALTER TABLE ONLY public.comments DROP CONSTRAINT fkdc17ddf4d9aa8e98;
ALTER TABLE ONLY public.comments DROP CONSTRAINT fkdc17ddf4ce12cae8;
ALTER TABLE ONLY public.comments DROP CONSTRAINT fkdc17ddf4793d9e77;
ALTER TABLE ONLY public.poll_result DROP CONSTRAINT fkd981c89df0ed6769;
ALTER TABLE ONLY public.poll_result DROP CONSTRAINT fkd981c89dddd118b5;
ALTER TABLE ONLY public.tweetpoll_save_published_status DROP CONSTRAINT fkd499a4b6953c854b;
ALTER TABLE ONLY public.tweetpoll_save_published_status DROP CONSTRAINT fkd499a4b65239d117;
ALTER TABLE ONLY public.project_group DROP CONSTRAINT fkc7652dd984536452;
ALTER TABLE ONLY public.project_group DROP CONSTRAINT fkc7652dd945895aff;
ALTER TABLE ONLY public.poll_folder DROP CONSTRAINT fkc5911cee6ef241e9;
ALTER TABLE ONLY public.poll_folder DROP CONSTRAINT fkc5911cee2b2a6ab4;
ALTER TABLE ONLY public.access_rate DROP CONSTRAINT fkc2760edbe4669675;
ALTER TABLE ONLY public.access_rate DROP CONSTRAINT fkc2760edb953c854b;
ALTER TABLE ONLY public.access_rate DROP CONSTRAINT fkc2760edb63976e9;
ALTER TABLE ONLY public.access_rate DROP CONSTRAINT fkc2760edb51153812;
ALTER TABLE ONLY public.dashboard DROP CONSTRAINT fkc18aea949229bca5;
ALTER TABLE ONLY public.survey_pagination DROP CONSTRAINT fkbec9a99f793d9e77;
ALTER TABLE ONLY public.survey_pagination DROP CONSTRAINT fkbec9a99f1359b877;
ALTER TABLE ONLY public.useraccount_permission DROP CONSTRAINT fkbe01ce4c5f77a117;
ALTER TABLE ONLY public.useraccount_permission DROP CONSTRAINT fkbe01ce4c43adb63d;
ALTER TABLE ONLY public.question_dependence_survey DROP CONSTRAINT fkbb424d49793d9e77;
ALTER TABLE ONLY public.groups DROP CONSTRAINT fkb63dd9d45ece45a2;
ALTER TABLE ONLY public.gadget DROP CONSTRAINT fkb549144cb975b5f9;
ALTER TABLE ONLY public.survey_group_format DROP CONSTRAINT fkb4df867cb1a6912c;
ALTER TABLE ONLY public.survey_group_format DROP CONSTRAINT fkb4df867c310e993c;
ALTER TABLE ONLY public.question_collection DROP CONSTRAINT fkb4097c972b2a6ab4;
ALTER TABLE ONLY public.client DROP CONSTRAINT fkaf12f3cb225a055;
ALTER TABLE ONLY public.useraccount DROP CONSTRAINT fka7d56be2b8eb1450;
ALTER TABLE ONLY public.useraccount DROP CONSTRAINT fka7d56be25ece45a2;
ALTER TABLE ONLY public.tweetpoll DROP CONSTRAINT fka65b1d0d9ba7e54;
ALTER TABLE ONLY public.tweetpoll DROP CONSTRAINT fka65b1d0a64fb606;
ALTER TABLE ONLY public.tweetpoll DROP CONSTRAINT fka65b1d050fe71f5;
ALTER TABLE ONLY public.tweetpoll DROP CONSTRAINT fka65b1d02b2a6ab4;
ALTER TABLE ONLY public.tweetpoll_folder DROP CONSTRAINT fka027a9dd6ef241e9;
ALTER TABLE ONLY public.tweetpoll_folder DROP CONSTRAINT fka027a9dd2b2a6ab4;
ALTER TABLE ONLY public.questions DROP CONSTRAINT fk95c5414d84133d82;
ALTER TABLE ONLY public.questions DROP CONSTRAINT fk95c5414d2b2a6ab4;
ALTER TABLE ONLY public.survey_result DROP CONSTRAINT fk92ea04a2eb8d35c9;
ALTER TABLE ONLY public.questions_dependencies DROP CONSTRAINT fk92e86adbddd118b5;
ALTER TABLE ONLY public.surveys DROP CONSTRAINT fk91914459b1a6912c;
ALTER TABLE ONLY public.surveys DROP CONSTRAINT fk91914459a64fb606;
ALTER TABLE ONLY public.surveys DROP CONSTRAINT fk91914459a3c7a06a;
ALTER TABLE ONLY public.surveys DROP CONSTRAINT fk919144592b2a6ab4;
ALTER TABLE ONLY public.attachment DROP CONSTRAINT fk8af75923225a055;
ALTER TABLE ONLY public.tweetpoll_switch DROP CONSTRAINT fk89f7b0a3ddd118b5;
ALTER TABLE ONLY public.tweetpoll_switch DROP CONSTRAINT fk89f7b0a3550299a;
ALTER TABLE ONLY public.tweetpoll_result DROP CONSTRAINT fk8749c18cb9d39f98;
ALTER TABLE ONLY public.gadget_properties DROP CONSTRAINT fk866b6706369f8b2c;
ALTER TABLE ONLY public.gadget_properties DROP CONSTRAINT fk866b670629091b05;
ALTER TABLE ONLY public.useraccount_followers DROP CONSTRAINT fk7f1957f8f44558e9;
ALTER TABLE ONLY public.useraccount_followers DROP CONSTRAINT fk7f1957f8e53fbc6;
ALTER TABLE ONLY public.groups_permission DROP CONSTRAINT fk7f1951a45895aff;
ALTER TABLE ONLY public.groups_permission DROP CONSTRAINT fk7f1951a43adb63d;
ALTER TABLE ONLY public.survey_folder DROP CONSTRAINT fk7ef958f36ef241e9;
ALTER TABLE ONLY public.survey_folder DROP CONSTRAINT fk7ef958f32b2a6ab4;
ALTER TABLE ONLY public.emaillist DROP CONSTRAINT fk7e5f425a2b2a6ab4;
ALTER TABLE ONLY public.application_connection DROP CONSTRAINT fk73d5d2d4402be26;
ALTER TABLE ONLY public.application_connection DROP CONSTRAINT fk73d5d2d27e933d7;
ALTER TABLE ONLY public.geopoint DROP CONSTRAINT fk6c73c0bfbd91661d;
ALTER TABLE ONLY public.geopoint DROP CONSTRAINT fk6c73c0bf5ece45a2;
ALTER TABLE ONLY public.geopoint DROP CONSTRAINT fk6c73c0bf34ef9a43;
ALTER TABLE ONLY public.application DROP CONSTRAINT fk5ca405505ece45a2;
ALTER TABLE ONLY public.email DROP CONSTRAINT fk5c24b9ced78e617;
ALTER TABLE ONLY public.questions_answers DROP CONSTRAINT fk539703837e6c7bbc;
ALTER TABLE ONLY public.geopoint_type DROP CONSTRAINT fk514326ba4075e3fd;
ALTER TABLE ONLY public.social_account DROP CONSTRAINT fk50078b5bf2f411f2;
ALTER TABLE ONLY public.social_account DROP CONSTRAINT fk50078b5b5ece45a2;
ALTER TABLE ONLY public.emailsubscribe DROP CONSTRAINT fk4b85010eed78e617;
ALTER TABLE ONLY public.emailsubscribe DROP CONSTRAINT fk4b85010ee824035;
ALTER TABLE ONLY public.group_permission DROP CONSTRAINT fk362e6f8f45895aff;
ALTER TABLE ONLY public.group_permission DROP CONSTRAINT fk362e6f8f43adb63d;
ALTER TABLE ONLY public.poll DROP CONSTRAINT fk3497bff44558e9;
ALTER TABLE ONLY public.poll DROP CONSTRAINT fk3497bfa64fb606;
ALTER TABLE ONLY public.poll DROP CONSTRAINT fk3497bf89452cca;
ALTER TABLE ONLY public.poll DROP CONSTRAINT fk3497bf50fe71f5;
ALTER TABLE ONLY public.hits DROP CONSTRAINT fk30df40953c854b;
ALTER TABLE ONLY public.hits DROP CONSTRAINT fk30df4063976e9;
ALTER TABLE ONLY public.hits DROP CONSTRAINT fk30df4051153812;
ALTER TABLE ONLY public.hits DROP CONSTRAINT fk30df4019aa125;
ALTER TABLE ONLY public.question_category_questions DROP CONSTRAINT fk2ffe1845b10e79be;
ALTER TABLE ONLY public.question_category_questions DROP CONSTRAINT fk2ffe18457a068cb;
ALTER TABLE ONLY public.project_geopoint DROP CONSTRAINT fk2599132584536452;
ALTER TABLE ONLY public.project_geopoint DROP CONSTRAINT fk2599132535313189;
ALTER TABLE ONLY public.project_locations DROP CONSTRAINT fk242951b884536452;
ALTER TABLE ONLY public.project_locations DROP CONSTRAINT fk242951b835313189;
ALTER TABLE ONLY public.notification DROP CONSTRAINT fk237a88eb2b2a6ab4;
ALTER TABLE ONLY public.question_relations DROP CONSTRAINT fk217954de8a76a0bd;
ALTER TABLE ONLY public.question_relations DROP CONSTRAINT fk217954de893521da;
ALTER TABLE ONLY public.survey_section_questions DROP CONSTRAINT fk12354ece4e3a9df5;
ALTER TABLE ONLY public.survey_section_questions DROP CONSTRAINT fk12354ece11057e56;
DROP INDEX public.usernameindex;
DROP INDEX public.emailindex;
ALTER TABLE ONLY public.useraccount DROP CONSTRAINT useraccount_username_key1;
ALTER TABLE ONLY public.useraccount DROP CONSTRAINT useraccount_username_key;
ALTER TABLE ONLY public.useraccount_project DROP CONSTRAINT useraccount_project_pkey;
ALTER TABLE ONLY public.useraccount DROP CONSTRAINT useraccount_pkey;
ALTER TABLE ONLY public.useraccount_permission DROP CONSTRAINT useraccount_permission_pkey;
ALTER TABLE ONLY public.useraccount_followers DROP CONSTRAINT useraccount_followers_pkey;
ALTER TABLE ONLY public.useraccount DROP CONSTRAINT useraccount_email_key;
ALTER TABLE ONLY public.tweetpoll_switch DROP CONSTRAINT tweetpoll_switch_tweet_code_key;
ALTER TABLE ONLY public.tweetpoll_switch DROP CONSTRAINT tweetpoll_switch_pkey;
ALTER TABLE ONLY public.tweetpoll_save_published_status DROP CONSTRAINT tweetpoll_save_published_status_pkey;
ALTER TABLE ONLY public.tweetpoll_result DROP CONSTRAINT tweetpoll_result_pkey;
ALTER TABLE ONLY public.tweetpoll DROP CONSTRAINT tweetpoll_pkey;
ALTER TABLE ONLY public.tweetpoll_hashtags DROP CONSTRAINT tweetpoll_hashtags_pkey;
ALTER TABLE ONLY public.tweetpoll_folder DROP CONSTRAINT tweetpoll_folder_pkey;
ALTER TABLE ONLY public.surveys DROP CONSTRAINT surveys_pkey;
ALTER TABLE ONLY public.survey_section_questions DROP CONSTRAINT survey_section_questions_pkey;
ALTER TABLE ONLY public.survey_section DROP CONSTRAINT survey_section_pkey;
ALTER TABLE ONLY public.survey_result DROP CONSTRAINT survey_result_pkey;
ALTER TABLE ONLY public.survey_pagination DROP CONSTRAINT survey_pagination_pkey;
ALTER TABLE ONLY public.survey_group_project DROP CONSTRAINT survey_group_project_pkey;
ALTER TABLE ONLY public.survey_group DROP CONSTRAINT survey_group_pkey;
ALTER TABLE ONLY public.survey_group_format DROP CONSTRAINT survey_group_format_pkey;
ALTER TABLE ONLY public.survey_format DROP CONSTRAINT survey_format_pkey;
ALTER TABLE ONLY public.survey_folder DROP CONSTRAINT survey_folder_pkey;
ALTER TABLE ONLY public.social_account DROP CONSTRAINT social_account_social_profile_id_key;
ALTER TABLE ONLY public.social_account DROP CONSTRAINT social_account_social_account_name_key;
ALTER TABLE ONLY public.social_account DROP CONSTRAINT social_account_pkey;
ALTER TABLE ONLY public.questions DROP CONSTRAINT questions_pkey;
ALTER TABLE ONLY public.questions_pattern DROP CONSTRAINT questions_pattern_pkey;
ALTER TABLE ONLY public.questions_dependencies DROP CONSTRAINT questions_dependencies_questionid_to_key;
ALTER TABLE ONLY public.questions_dependencies DROP CONSTRAINT questions_dependencies_questionid_from_key;
ALTER TABLE ONLY public.questions_dependencies DROP CONSTRAINT questions_dependencies_pkey;
ALTER TABLE ONLY public.questions_dependencies DROP CONSTRAINT questions_dependencies_descriptiondependence_key;
ALTER TABLE ONLY public.questions_answers DROP CONSTRAINT questions_answers_pkey;
ALTER TABLE ONLY public.question_relations DROP CONSTRAINT question_relations_pkey;
ALTER TABLE ONLY public.question_dependence_survey DROP CONSTRAINT question_dependence_survey_pkey;
ALTER TABLE ONLY public.question_collection DROP CONSTRAINT question_collection_pkey;
ALTER TABLE ONLY public.question_category_questions DROP CONSTRAINT question_category_questions_pkey;
ALTER TABLE ONLY public.question_category DROP CONSTRAINT question_category_pkey;
ALTER TABLE ONLY public.project DROP CONSTRAINT project_pkey;
ALTER TABLE ONLY public.project_locations DROP CONSTRAINT project_locations_pkey;
ALTER TABLE ONLY public.project_group DROP CONSTRAINT project_group_pkey;
ALTER TABLE ONLY public.project_geopoint DROP CONSTRAINT project_geopoint_pkey;
ALTER TABLE ONLY public.poll_result DROP CONSTRAINT poll_result_pkey;
ALTER TABLE ONLY public.poll DROP CONSTRAINT poll_poll_hash_key;
ALTER TABLE ONLY public.poll DROP CONSTRAINT poll_pkey;
ALTER TABLE ONLY public.poll_folder DROP CONSTRAINT poll_folder_pkey;
ALTER TABLE ONLY public.permission DROP CONSTRAINT permission_pkey;
ALTER TABLE ONLY public.notification DROP CONSTRAINT notification_pkey;
ALTER TABLE ONLY public.hits DROP CONSTRAINT hits_pkey;
ALTER TABLE ONLY public.hash_tags DROP CONSTRAINT hash_tags_pkey;
ALTER TABLE ONLY public.groups DROP CONSTRAINT groups_pkey;
ALTER TABLE ONLY public.groups_permission DROP CONSTRAINT groups_permission_pkey;
ALTER TABLE ONLY public.group_permission DROP CONSTRAINT group_permission_pkey;
ALTER TABLE ONLY public.geopoint_type DROP CONSTRAINT geopoint_type_pkey;
ALTER TABLE ONLY public.geopoint DROP CONSTRAINT geopoint_pkey;
ALTER TABLE ONLY public.geopoint_folder DROP CONSTRAINT geopoint_folder_pkey;
ALTER TABLE ONLY public.gadget_properties DROP CONSTRAINT gadget_properties_pkey;
ALTER TABLE ONLY public.gadget DROP CONSTRAINT gadget_pkey;
ALTER TABLE ONLY public.emailsubscribe DROP CONSTRAINT emailsubscribe_pkey;
ALTER TABLE ONLY public.emaillist DROP CONSTRAINT emaillist_pkey;
ALTER TABLE ONLY public.email DROP CONSTRAINT email_pkey;
ALTER TABLE ONLY public.email DROP CONSTRAINT email_email_key;
ALTER TABLE ONLY public.dashboard DROP CONSTRAINT dashboard_pkey;
ALTER TABLE ONLY public.comments DROP CONSTRAINT comments_pkey;
ALTER TABLE ONLY public.client DROP CONSTRAINT client_pkey;
ALTER TABLE ONLY public.attachment DROP CONSTRAINT attachment_pkey;
ALTER TABLE ONLY public.application DROP CONSTRAINT application_pkey;
ALTER TABLE ONLY public.application_connection DROP CONSTRAINT application_connection_pkey;
ALTER TABLE ONLY public.account DROP CONSTRAINT account_pkey;
ALTER TABLE ONLY public.access_rate DROP CONSTRAINT access_rate_pkey;
DROP TABLE public.useraccount_project;
DROP TABLE public.useraccount_permission;
DROP TABLE public.useraccount_followers;
DROP TABLE public.useraccount;
DROP TABLE public.tweetpoll_switch;
DROP TABLE public.tweetpoll_save_published_status;
DROP TABLE public.tweetpoll_result;
DROP TABLE public.tweetpoll_hashtags;
DROP TABLE public.tweetpoll_folder;
DROP TABLE public.tweetpoll;
DROP TABLE public.surveys;
DROP TABLE public.survey_section_questions;
DROP TABLE public.survey_section;
DROP TABLE public.survey_result;
DROP TABLE public.survey_pagination;
DROP TABLE public.survey_group_project;
DROP TABLE public.survey_group_format;
DROP TABLE public.survey_group;
DROP TABLE public.survey_format;
DROP TABLE public.survey_folder;
DROP TABLE public.social_account;
DROP TABLE public.questions_pattern;
DROP TABLE public.questions_dependencies;
DROP TABLE public.questions_answers;
DROP TABLE public.questions;
DROP TABLE public.question_relations;
DROP TABLE public.question_dependence_survey;
DROP TABLE public.question_collection;
DROP TABLE public.question_category_questions;
DROP TABLE public.question_category;
DROP TABLE public.project_locations;
DROP TABLE public.project_group;
DROP TABLE public.project_geopoint;
DROP TABLE public.project;
DROP TABLE public.poll_result;
DROP TABLE public.poll_folder;
DROP TABLE public.poll;
DROP TABLE public.permission;
DROP TABLE public.notification;
DROP TABLE public.hits;
DROP SEQUENCE public.hibernate_sequence;
DROP TABLE public.hash_tags;
DROP TABLE public.groups_permission;
DROP TABLE public.groups;
DROP TABLE public.group_permission;
DROP TABLE public.geopoint_type;
DROP TABLE public.geopoint_folder;
DROP TABLE public.geopoint;
DROP TABLE public.gadget_properties;
DROP TABLE public.gadget;
DROP TABLE public.emailsubscribe;
DROP TABLE public.emaillist;
DROP TABLE public.email;
DROP TABLE public.dashboard;
DROP TABLE public.comments;
DROP TABLE public.client;
DROP TABLE public.attachment;
DROP TABLE public.application_connection;
DROP TABLE public.application;
DROP TABLE public.account;
DROP TABLE public.access_rate;