package org.encuestame.utils.oauth;

public class AuthorizedRequestToken {

    private final OAuthToken requestToken;

    private final String verifier;

    /**
     * Creates an authorized request token.
     * @param requestToken the request token object
     * @param verifier the verifier returned by the provider after user authorization (OAuth 1.0 only)
     */
    public AuthorizedRequestToken(OAuthToken requestToken, String verifier) {
        this.requestToken = requestToken;
        this.verifier = verifier;
    }

    /**
     * The request token value.
     */
    public String getValue() {
        return requestToken.getValue();
    }

    /**
     * The request token secret.
     * OAuth 1.0 only.
     */
    public String getSecret() {
        return requestToken.getSecret();
    }

    /**
     * The verifier string generated by the provider.
     * OAuth 1.0 only.
     */
    public String getVerifier() {
        return verifier;
    }

}