<%@ include file="/WEB-INF/jsp/includes/taglibs.jsp"%>
<c:if test="${!development}">
    <!-- File generated by dojo build-->
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/stats/GenericStats.js"></script>
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/hashtags/HashTagGraph.js"></script>
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/menu/TimeRangeDropDownMenu.js"></script>
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/publications/Publications.js"></script>
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/social/LinksPublished.js"></script>
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/stats/RatePosition.js"></script>
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/stats/TopProfiles.js"></script>
</c:if>

