<div class="updateProfile">
        FORMULARIO ACTUALIZACION
        <h1>Please upload a file</h1>
        <form method="post" action="/encuestame/user/profile/file/upload" enctype="multipart/form-data" id="imageForm">
              <input type="file" name="file" onkeydown="javascript:return false;"/>
              <input type="button" value="Upload" dojoAttachEvent="onclick:_uploadImage"
        </form>
</div>