package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * CatLocationUser generated by hbm2java
 */
public class CatLocationUser implements java.io.Serializable {

	private CatLocationUserId id;
	private Proyect proyect;
	private SecUsers secUsers;
	private CatLocation catLocation;

	public CatLocationUser() {
	}

	public CatLocationUser(CatLocationUserId id, Proyect proyect,
			SecUsers secUsers, CatLocation catLocation) {
		this.id = id;
		this.proyect = proyect;
		this.secUsers = secUsers;
		this.catLocation = catLocation;
	}

	public CatLocationUserId getId() {
		return this.id;
	}

	public void setId(CatLocationUserId id) {
		this.id = id;
	}

	public Proyect getProyect() {
		return this.proyect;
	}

	public void setProyect(Proyect proyect) {
		this.proyect = proyect;
	}

	public SecUsers getSecUsers() {
		return this.secUsers;
	}

	public void setSecUsers(SecUsers secUsers) {
		this.secUsers = secUsers;
	}

	public CatLocation getCatLocation() {
		return this.catLocation;
	}

	public void setCatLocation(CatLocation catLocation) {
		this.catLocation = catLocation;
	}

}
