package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * CatLocationUser generated by hbm2java
 */
public class CatLocationUser implements java.io.Serializable {

	private CatLocationUserId id;
	private int idState;

	public CatLocationUser() {
	}

	public CatLocationUser(CatLocationUserId id, int idState) {
		this.id = id;
		this.idState = idState;
	}

	public CatLocationUserId getId() {
		return this.id;
	}

	public void setId(CatLocationUserId id) {
		this.id = id;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

}
