package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CatLocationType generated by hbm2java
 */
public class CatLocationType implements java.io.Serializable {

	private String tidtype;
	private String description;
	private Integer level;
	private Set<CatLocation> catLocations = new HashSet<CatLocation>(0);

	public CatLocationType() {
	}

	public CatLocationType(String tidtype) {
		this.tidtype = tidtype;
	}

	public CatLocationType(String tidtype, String description, Integer level,
			Set<CatLocation> catLocations) {
		this.tidtype = tidtype;
		this.description = description;
		this.level = level;
		this.catLocations = catLocations;
	}

	public String getTidtype() {
		return this.tidtype;
	}

	public void setTidtype(String tidtype) {
		this.tidtype = tidtype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Set<CatLocation> getCatLocations() {
		return this.catLocations;
	}

	public void setCatLocations(Set<CatLocation> catLocations) {
		this.catLocations = catLocations;
	}

}
