package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * CatLocation generated by hbm2java
 */
public class CatLocation implements java.io.Serializable {

	private int tid;
	private String tidtype;
	private String description;
	private int level;
	private String active;
	private int idState;
	private Integer govId;
	private Float lat;
	private Float lng;
	private String topographySheet;

	public CatLocation() {
	}

	public CatLocation(int tid, String tidtype, String description, int level,
			String active, int idState) {
		this.tid = tid;
		this.tidtype = tidtype;
		this.description = description;
		this.level = level;
		this.active = active;
		this.idState = idState;
	}

	public CatLocation(int tid, String tidtype, String description, int level,
			String active, int idState, Integer govId, Float lat, Float lng,
			String topographySheet) {
		this.tid = tid;
		this.tidtype = tidtype;
		this.description = description;
		this.level = level;
		this.active = active;
		this.idState = idState;
		this.govId = govId;
		this.lat = lat;
		this.lng = lng;
		this.topographySheet = topographySheet;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public String getTidtype() {
		return this.tidtype;
	}

	public void setTidtype(String tidtype) {
		this.tidtype = tidtype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public Integer getGovId() {
		return this.govId;
	}

	public void setGovId(Integer govId) {
		this.govId = govId;
	}

	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	public Float getLng() {
		return this.lng;
	}

	public void setLng(Float lng) {
		this.lng = lng;
	}

	public String getTopographySheet() {
		return this.topographySheet;
	}

	public void setTopographySheet(String topographySheet) {
		this.topographySheet = topographySheet;
	}

}
