package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

/**
 * CatLocationUserId generated by hbm2java
 */
public class CatLocationUserId implements java.io.Serializable {

	private int tid;
	private int proyectId;
	private int uid;

	public CatLocationUserId() {
	}

	public CatLocationUserId(int tid, int proyectId, int uid) {
		this.tid = tid;
		this.proyectId = proyectId;
		this.uid = uid;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public int getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(int proyectId) {
		this.proyectId = proyectId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatLocationUserId))
			return false;
		CatLocationUserId castOther = (CatLocationUserId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getProyectId() == castOther.getProyectId())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getProyectId();
		result = 37 * result + this.getUid();
		return result;
	}

}
