package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * CatLocation generated by hbm2java
 */
public class CatLocation implements java.io.Serializable {

	private int locateId;
	private String tidtype;
	private String description;
	private int level;
	private String active;
	private Float lat;
	private Float lng;

	public CatLocation() {
	}

	public CatLocation(int locateId, String tidtype, String description,
			int level) {
		this.locateId = locateId;
		this.tidtype = tidtype;
		this.description = description;
		this.level = level;
	}

	public CatLocation(int locateId, String tidtype, String description,
			int level, String active, Float lat, Float lng) {
		this.locateId = locateId;
		this.tidtype = tidtype;
		this.description = description;
		this.level = level;
		this.active = active;
		this.lat = lat;
		this.lng = lng;
	}

	public int getLocateId() {
		return this.locateId;
	}

	public void setLocateId(int locateId) {
		this.locateId = locateId;
	}

	public String getTidtype() {
		return this.tidtype;
	}

	public void setTidtype(String tidtype) {
		this.tidtype = tidtype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	public Float getLng() {
		return this.lng;
	}

	public void setLng(Float lng) {
		this.lng = lng;
	}

}
