package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * CatLocationType generated by hbm2java
 */
public class CatLocationType implements java.io.Serializable {

	private String locIdType;
	private String description;
	private Integer level;

	public CatLocationType() {
	}

	public CatLocationType(String locIdType) {
		this.locIdType = locIdType;
	}

	public CatLocationType(String locIdType, String description, Integer level) {
		this.locIdType = locIdType;
		this.description = description;
		this.level = level;
	}

	public String getLocIdType() {
		return this.locIdType;
	}

	public void setLocIdType(String locIdType) {
		this.locIdType = locIdType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

}
