package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CatState generated by hbm2java
 */
public class CatState implements java.io.Serializable {

	private Integer idState;
	private String descState;
	private String image;
	private Set<Surveys> surveyses = new HashSet<Surveys>(0);
	private Set<SecUsers> secUserses = new HashSet<SecUsers>(0);
	private Set<Proyect> proyects = new HashSet<Proyect>(0);
	private Set<CatLocation> catLocations = new HashSet<CatLocation>(0);
	private Set<Questions> questionses = new HashSet<Questions>(0);

	public CatState() {
	}

	public CatState(String descState, String image, Set<Surveys> surveyses,
			Set<SecUsers> secUserses, Set<Proyect> proyects,
			Set<CatLocation> catLocations, Set<Questions> questionses) {
		this.descState = descState;
		this.image = image;
		this.surveyses = surveyses;
		this.secUserses = secUserses;
		this.proyects = proyects;
		this.catLocations = catLocations;
		this.questionses = questionses;
	}

	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	public String getDescState() {
		return this.descState;
	}

	public void setDescState(String descState) {
		this.descState = descState;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set<Surveys> getSurveyses() {
		return this.surveyses;
	}

	public void setSurveyses(Set<Surveys> surveyses) {
		this.surveyses = surveyses;
	}

	public Set<SecUsers> getSecUserses() {
		return this.secUserses;
	}

	public void setSecUserses(Set<SecUsers> secUserses) {
		this.secUserses = secUserses;
	}

	public Set<Proyect> getProyects() {
		return this.proyects;
	}

	public void setProyects(Set<Proyect> proyects) {
		this.proyects = proyects;
	}

	public Set<CatLocation> getCatLocations() {
		return this.catLocations;
	}

	public void setCatLocations(Set<CatLocation> catLocations) {
		this.catLocations = catLocations;
	}

	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

}
