package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * CatState generated by hbm2java
 */
public class CatState implements java.io.Serializable {

	private Integer idEstado;
	private String descEstado;
	private String image;

	public CatState() {
	}

	public CatState(String descEstado, String image) {
		this.descEstado = descEstado;
		this.image = image;
	}

	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	public String getDescEstado() {
		return this.descEstado;
	}

	public void setDescEstado(String descEstado) {
		this.descEstado = descEstado;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
