package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ErrorReports generated by hbm2java
 */
public class ErrorReports implements java.io.Serializable {

	private Integer id;
	private String domain;
	private String pageUrl;
	private String reportedBy;
	private String reportedOn;
	private String fixedBy;
	private String fixedOn;
	private String timeTaken;
	private String location;
	private String category;
	private String description;
	private String isBrowser;
	private String cause;
	private String solution;
	private String severity;
	private String incorrectSolution;
	private String ownedByUs;
	private String reporterComments;
	private String errorDetails;
	private String fixerComments;
	private String isFixed;
	private Date timeStamp;

	public ErrorReports() {
	}

	public ErrorReports(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public ErrorReports(String domain, String pageUrl, String reportedBy,
			String reportedOn, String fixedBy, String fixedOn,
			String timeTaken, String location, String category,
			String description, String isBrowser, String cause,
			String solution, String severity, String incorrectSolution,
			String ownedByUs, String reporterComments, String errorDetails,
			String fixerComments, String isFixed, Date timeStamp) {
		this.domain = domain;
		this.pageUrl = pageUrl;
		this.reportedBy = reportedBy;
		this.reportedOn = reportedOn;
		this.fixedBy = fixedBy;
		this.fixedOn = fixedOn;
		this.timeTaken = timeTaken;
		this.location = location;
		this.category = category;
		this.description = description;
		this.isBrowser = isBrowser;
		this.cause = cause;
		this.solution = solution;
		this.severity = severity;
		this.incorrectSolution = incorrectSolution;
		this.ownedByUs = ownedByUs;
		this.reporterComments = reporterComments;
		this.errorDetails = errorDetails;
		this.fixerComments = fixerComments;
		this.isFixed = isFixed;
		this.timeStamp = timeStamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	public String getReportedBy() {
		return this.reportedBy;
	}

	public void setReportedBy(String reportedBy) {
		this.reportedBy = reportedBy;
	}

	public String getReportedOn() {
		return this.reportedOn;
	}

	public void setReportedOn(String reportedOn) {
		this.reportedOn = reportedOn;
	}

	public String getFixedBy() {
		return this.fixedBy;
	}

	public void setFixedBy(String fixedBy) {
		this.fixedBy = fixedBy;
	}

	public String getFixedOn() {
		return this.fixedOn;
	}

	public void setFixedOn(String fixedOn) {
		this.fixedOn = fixedOn;
	}

	public String getTimeTaken() {
		return this.timeTaken;
	}

	public void setTimeTaken(String timeTaken) {
		this.timeTaken = timeTaken;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIsBrowser() {
		return this.isBrowser;
	}

	public void setIsBrowser(String isBrowser) {
		this.isBrowser = isBrowser;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public String getSolution() {
		return this.solution;
	}

	public void setSolution(String solution) {
		this.solution = solution;
	}

	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	public String getIncorrectSolution() {
		return this.incorrectSolution;
	}

	public void setIncorrectSolution(String incorrectSolution) {
		this.incorrectSolution = incorrectSolution;
	}

	public String getOwnedByUs() {
		return this.ownedByUs;
	}

	public void setOwnedByUs(String ownedByUs) {
		this.ownedByUs = ownedByUs;
	}

	public String getReporterComments() {
		return this.reporterComments;
	}

	public void setReporterComments(String reporterComments) {
		this.reporterComments = reporterComments;
	}

	public String getErrorDetails() {
		return this.errorDetails;
	}

	public void setErrorDetails(String errorDetails) {
		this.errorDetails = errorDetails;
	}

	public String getFixerComments() {
		return this.fixerComments;
	}

	public void setFixerComments(String fixerComments) {
		this.fixerComments = fixerComments;
	}

	public String getIsFixed() {
		return this.isFixed;
	}

	public void setIsFixed(String isFixed) {
		this.isFixed = isFixed;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

}
