package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * IpTrack generated by hbm2java
 */
public class IpTrack implements java.io.Serializable {

	private IpTrackId id;
	private String ip;
	private int completed;
	private Date fechaIngreso;

	public IpTrack() {
	}

	public IpTrack(IpTrackId id, int completed, Date fechaIngreso) {
		this.id = id;
		this.completed = completed;
		this.fechaIngreso = fechaIngreso;
	}

	public IpTrack(IpTrackId id, String ip, int completed, Date fechaIngreso) {
		this.id = id;
		this.ip = ip;
		this.completed = completed;
		this.fechaIngreso = fechaIngreso;
	}

	public IpTrackId getId() {
		return this.id;
	}

	public void setId(IpTrackId id) {
		this.id = id;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getCompleted() {
		return this.completed;
	}

	public void setCompleted(int completed) {
		this.completed = completed;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
