package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

/**
 * IpTrackId generated by hbm2java
 */
public class IpTrackId implements java.io.Serializable {

	private int sid;
	private int uid;

	public IpTrackId() {
	}

	public IpTrackId(int sid, int uid) {
		this.sid = sid;
		this.uid = uid;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IpTrackId))
			return false;
		IpTrackId castOther = (IpTrackId) other;

		return (this.getSid() == castOther.getSid())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSid();
		result = 37 * result + this.getUid();
		return result;
	}

}
