package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProyectUser generated by hbm2java
 */
public class ProjectUser implements java.io.Serializable {

	private ProjectUserId id;
	private Project proyect;
	private SecUsers secUsers;
	private Date dateNew;

	public ProjectUser() {
	}

	public ProjectUser(ProjectUserId id, Project proyect, SecUsers secUsers,
			Date dateNew) {
		this.id = id;
		this.proyect = proyect;
		this.secUsers = secUsers;
		this.dateNew = dateNew;
	}

	public ProjectUserId getId() {
		return this.id;
	}

	public void setId(ProjectUserId id) {
		this.id = id;
	}

	public Project getProyect() {
		return this.proyect;
	}

	public void setProyect(Project proyect) {
		this.proyect = proyect;
	}

	public SecUsers getSecUsers() {
		return this.secUsers;
	}

	public void setSecUsers(SecUsers secUsers) {
		this.secUsers = secUsers;
	}

	public Date getDateNew() {
		return this.dateNew;
	}

	public void setDateNew(Date dateNew) {
		this.dateNew = dateNew;
	}

}
