package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyect generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer proyectId;
	private CatState catState;
	private String description;
	private String info;
	private Date dateStart;
	private byte[] logo;
	private String header;
	private String range;
	private Set<ProjectLocation> proyectLocations = new HashSet<ProjectLocation>(
			0);
	private Set<Surveys> surveyses = new HashSet<Surveys>(0);
	private Set<ProjectGroup> proyectGroups = new HashSet<ProjectGroup>(0);
	private Set<SurveyLocation> surveyLocations = new HashSet<SurveyLocation>(0);
	private Set<ProjectTypeSurvey> proyectTypeSurveies = new HashSet<ProjectTypeSurvey>(
			0);
	private Set<CatLocationUser> catLocationUsers = new HashSet<CatLocationUser>(
			0);
	private Set<ProjectUser> proyectUsers = new HashSet<ProjectUser>(0);

	public Project() {
	}

	public Project(CatState catState, String description, String info,
			Date dateStart) {
		this.catState = catState;
		this.description = description;
		this.info = info;
		this.dateStart = dateStart;
	}

	public Project(CatState catState, String description, String info,
			Date dateStart, byte[] logo, String header, String range,
			Set<ProjectLocation> proyectLocations, Set<Surveys> surveyses,
			Set<ProjectGroup> proyectGroups,
			Set<SurveyLocation> surveyLocations,
			Set<ProjectTypeSurvey> proyectTypeSurveies,
			Set<CatLocationUser> catLocationUsers, Set<ProjectUser> proyectUsers) {
		this.catState = catState;
		this.description = description;
		this.info = info;
		this.dateStart = dateStart;
		this.logo = logo;
		this.header = header;
		this.range = range;
		this.proyectLocations = proyectLocations;
		this.surveyses = surveyses;
		this.proyectGroups = proyectGroups;
		this.surveyLocations = surveyLocations;
		this.proyectTypeSurveies = proyectTypeSurveies;
		this.catLocationUsers = catLocationUsers;
		this.proyectUsers = proyectUsers;
	}

	public Integer getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(Integer proyectId) {
		this.proyectId = proyectId;
	}

	public CatState getCatState() {
		return this.catState;
	}

	public void setCatState(CatState catState) {
		this.catState = catState;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	public Set<ProjectLocation> getProyectLocations() {
		return this.proyectLocations;
	}

	public void setProyectLocations(Set<ProjectLocation> proyectLocations) {
		this.proyectLocations = proyectLocations;
	}

	public Set<Surveys> getSurveyses() {
		return this.surveyses;
	}

	public void setSurveyses(Set<Surveys> surveyses) {
		this.surveyses = surveyses;
	}

	public Set<ProjectGroup> getProyectGroups() {
		return this.proyectGroups;
	}

	public void setProyectGroups(Set<ProjectGroup> proyectGroups) {
		this.proyectGroups = proyectGroups;
	}

	public Set<SurveyLocation> getSurveyLocations() {
		return this.surveyLocations;
	}

	public void setSurveyLocations(Set<SurveyLocation> surveyLocations) {
		this.surveyLocations = surveyLocations;
	}

	public Set<ProjectTypeSurvey> getProyectTypeSurveies() {
		return this.proyectTypeSurveies;
	}

	public void setProyectTypeSurveies(
			Set<ProjectTypeSurvey> proyectTypeSurveies) {
		this.proyectTypeSurveies = proyectTypeSurveies;
	}

	public Set<CatLocationUser> getCatLocationUsers() {
		return this.catLocationUsers;
	}

	public void setCatLocationUsers(Set<CatLocationUser> catLocationUsers) {
		this.catLocationUsers = catLocationUsers;
	}

	public Set<ProjectUser> getProyectUsers() {
		return this.proyectUsers;
	}

	public void setProyectUsers(Set<ProjectUser> proyectUsers) {
		this.proyectUsers = proyectUsers;
	}

}
