package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProjectUser generated by hbm2java
 */
public class ProjectUser implements java.io.Serializable {

	private ProjectUserId id;
	private Project project;
	private SecUsers secUsers;
	private Date dateNew;

	public ProjectUser() {
	}

	public ProjectUser(ProjectUserId id, Project project, SecUsers secUsers,
			Date dateNew) {
		this.id = id;
		this.project = project;
		this.secUsers = secUsers;
		this.dateNew = dateNew;
	}

	public ProjectUserId getId() {
		return this.id;
	}

	public void setId(ProjectUserId id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public SecUsers getSecUsers() {
		return this.secUsers;
	}

	public void setSecUsers(SecUsers secUsers) {
		this.secUsers = secUsers;
	}

	public Date getDateNew() {
		return this.dateNew;
	}

	public void setDateNew(Date dateNew) {
		this.dateNew = dateNew;
	}

}
