package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProyectGroup generated by hbm2java
 */
public class ProjectGroup implements java.io.Serializable {

	private ProjectGroupId id;
	private Project proyect;
	private SecGroups secGroups;
	private Date fechaIngreso;

	public ProjectGroup() {
	}

	public ProjectGroup(ProjectGroupId id, Project proyect,
			SecGroups secGroups, Date fechaIngreso) {
		this.id = id;
		this.proyect = proyect;
		this.secGroups = secGroups;
		this.fechaIngreso = fechaIngreso;
	}

	public ProjectGroupId getId() {
		return this.id;
	}

	public void setId(ProjectGroupId id) {
		this.id = id;
	}

	public Project getProyect() {
		return this.proyect;
	}

	public void setProyect(Project proyect) {
		this.proyect = proyect;
	}

	public SecGroups getSecGroups() {
		return this.secGroups;
	}

	public void setSecGroups(SecGroups secGroups) {
		this.secGroups = secGroups;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
