package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * ProyectLocationId generated by hbm2java
 */
public class ProjectLocationId implements java.io.Serializable {

	private int tid;
	private int proyectId;

	public ProjectLocationId() {
	}

	public ProjectLocationId(int tid, int proyectId) {
		this.tid = tid;
		this.proyectId = proyectId;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public int getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(int proyectId) {
		this.proyectId = proyectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectLocationId))
			return false;
		ProjectLocationId castOther = (ProjectLocationId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getProyectId() == castOther.getProyectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getProyectId();
		return result;
	}

}
