package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * ProyectTypeSurvey generated by hbm2java
 */
public class ProjectTypeSurvey implements java.io.Serializable {

	private ProjectTypeSurveyId id;
	private Project proyect;
	private SurveyType surveyType;
	private boolean state;

	public ProjectTypeSurvey() {
	}

	public ProjectTypeSurvey(ProjectTypeSurveyId id, Project proyect,
			SurveyType surveyType, boolean state) {
		this.id = id;
		this.proyect = proyect;
		this.surveyType = surveyType;
		this.state = state;
	}

	public ProjectTypeSurveyId getId() {
		return this.id;
	}

	public void setId(ProjectTypeSurveyId id) {
		this.id = id;
	}

	public Project getProyect() {
		return this.proyect;
	}

	public void setProyect(Project proyect) {
		this.proyect = proyect;
	}

	public SurveyType getSurveyType() {
		return this.surveyType;
	}

	public void setSurveyType(SurveyType surveyType) {
		this.surveyType = surveyType;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

}
