package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProjectGroup generated by hbm2java
 */
public class ProjectGroup implements java.io.Serializable {

	private ProjectGroupId id;
	private Project project;
	private SecGroups secGroups;
	private Date fechaIngreso;

	public ProjectGroup() {
	}

	public ProjectGroup(ProjectGroupId id, Project project,
			SecGroups secGroups, Date fechaIngreso) {
		this.id = id;
		this.project = project;
		this.secGroups = secGroups;
		this.fechaIngreso = fechaIngreso;
	}

	public ProjectGroupId getId() {
		return this.id;
	}

	public void setId(ProjectGroupId id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public SecGroups getSecGroups() {
		return this.secGroups;
	}

	public void setSecGroups(SecGroups secGroups) {
		this.secGroups = secGroups;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
