package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * ProyectGroupId generated by hbm2java
 */
public class ProjectGroupId implements java.io.Serializable {

	private int groupId;
	private int proyectId;

	public ProjectGroupId() {
	}

	public ProjectGroupId(int groupId, int proyectId) {
		this.groupId = groupId;
		this.proyectId = proyectId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public int getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(int proyectId) {
		this.proyectId = proyectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectGroupId))
			return false;
		ProjectGroupId castOther = (ProjectGroupId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& (this.getProyectId() == castOther.getProyectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getProyectId();
		return result;
	}

}
