package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * ProyectLocation generated by hbm2java
 */
public class ProjectLocation implements java.io.Serializable {

	private ProjectLocationId id;
	private Project proyect;
	private CatLocation catLocation;
	private int idEstado;

	public ProjectLocation() {
	}

	public ProjectLocation(ProjectLocationId id, Project proyect,
			CatLocation catLocation, int idEstado) {
		this.id = id;
		this.proyect = proyect;
		this.catLocation = catLocation;
		this.idEstado = idEstado;
	}

	public ProjectLocationId getId() {
		return this.id;
	}

	public void setId(ProjectLocationId id) {
		this.id = id;
	}

	public Project getProyect() {
		return this.proyect;
	}

	public void setProyect(Project proyect) {
		this.proyect = proyect;
	}

	public CatLocation getCatLocation() {
		return this.catLocation;
	}

	public void setCatLocation(CatLocation catLocation) {
		this.catLocation = catLocation;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

}
