package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * ProjectLocation generated by hbm2java
 */
public class ProjectLocation implements java.io.Serializable {

	private ProjectLocationId id;
	private Project project;
	private SecGroups secGroups;
	private int idState;

	public ProjectLocation() {
	}

	public ProjectLocation(ProjectLocationId id, Project project,
			SecGroups secGroups, int idState) {
		this.id = id;
		this.project = project;
		this.secGroups = secGroups;
		this.idState = idState;
	}

	public ProjectLocationId getId() {
		return this.id;
	}

	public void setId(ProjectLocationId id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public SecGroups getSecGroups() {
		return this.secGroups;
	}

	public void setSecGroups(SecGroups secGroups) {
		this.secGroups = secGroups;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

}
