package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ProyectLocationId generated by hbm2java
 */
public class ProyectLocationId implements java.io.Serializable {

	private int tid;
	private int siteid;

	public ProyectLocationId() {
	}

	public ProyectLocationId(int tid, int siteid) {
		this.tid = tid;
		this.siteid = siteid;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectLocationId))
			return false;
		ProyectLocationId castOther = (ProyectLocationId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getSiteid() == castOther.getSiteid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getSiteid();
		return result;
	}

}
