package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProyectUser generated by hbm2java
 */
public class ProyectUser implements java.io.Serializable {

	private ProyectUserId id;
	private Date fechaIngreso;
	private int idEstado;

	public ProyectUser() {
	}

	public ProyectUser(ProyectUserId id, Date fechaIngreso, int idEstado) {
		this.id = id;
		this.fechaIngreso = fechaIngreso;
		this.idEstado = idEstado;
	}

	public ProyectUserId getId() {
		return this.id;
	}

	public void setId(ProyectUserId id) {
		this.id = id;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

}
