package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * ProyectTypeSurveyId generated by hbm2java
 */
public class ProyectTypeSurveyId implements java.io.Serializable {

	private int proyectId;
	private int stid;

	public ProyectTypeSurveyId() {
	}

	public ProyectTypeSurveyId(int proyectId, int stid) {
		this.proyectId = proyectId;
		this.stid = stid;
	}

	public int getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(int proyectId) {
		this.proyectId = proyectId;
	}

	public int getStid() {
		return this.stid;
	}

	public void setStid(int stid) {
		this.stid = stid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectTypeSurveyId))
			return false;
		ProyectTypeSurveyId castOther = (ProyectTypeSurveyId) other;

		return (this.getProyectId() == castOther.getProyectId())
				&& (this.getStid() == castOther.getStid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProyectId();
		result = 37 * result + this.getStid();
		return result;
	}

}
