package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProyectGroup generated by hbm2java
 */
public class ProyectGroup implements java.io.Serializable {

	private ProyectGroupId id;
	private Proyect proyect;
	private SecGroups secGroups;
	private Date fechaIngreso;

	public ProyectGroup() {
	}

	public ProyectGroup(ProyectGroupId id, Proyect proyect,
			SecGroups secGroups, Date fechaIngreso) {
		this.id = id;
		this.proyect = proyect;
		this.secGroups = secGroups;
		this.fechaIngreso = fechaIngreso;
	}

	public ProyectGroupId getId() {
		return this.id;
	}

	public void setId(ProyectGroupId id) {
		this.id = id;
	}

	public Proyect getProyect() {
		return this.proyect;
	}

	public void setProyect(Proyect proyect) {
		this.proyect = proyect;
	}

	public SecGroups getSecGroups() {
		return this.secGroups;
	}

	public void setSecGroups(SecGroups secGroups) {
		this.secGroups = secGroups;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
