package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Proyect generated by hbm2java
 */
public class Proyect implements java.io.Serializable {

	private Integer siteid;
	private String description;
	private String info;
	private Date dateStart;
	private int idState;
	private byte[] logo;
	private String header;
	private String range;

	public Proyect() {
	}

	public Proyect(String description, String info, Date dateStart, int idState) {
		this.description = description;
		this.info = info;
		this.dateStart = dateStart;
		this.idState = idState;
	}

	public Proyect(String description, String info, Date dateStart,
			int idState, byte[] logo, String header, String range) {
		this.description = description;
		this.info = info;
		this.dateStart = dateStart;
		this.idState = idState;
		this.logo = logo;
		this.header = header;
		this.range = range;
	}

	public Integer getSiteid() {
		return this.siteid;
	}

	public void setSiteid(Integer siteid) {
		this.siteid = siteid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

}
