package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * QuestionsSectionDetail generated by hbm2java
 */
public class QuestionsSectionDetail implements java.io.Serializable {

	private int qidDetalle;
	private Integer qid;
	private Integer ssid;
	private String nopreg;
	private String templateSec;

	public QuestionsSectionDetail() {
	}

	public QuestionsSectionDetail(int qidDetalle) {
		this.qidDetalle = qidDetalle;
	}

	public QuestionsSectionDetail(int qidDetalle, Integer qid, Integer ssid,
			String nopreg, String templateSec) {
		this.qidDetalle = qidDetalle;
		this.qid = qid;
		this.ssid = ssid;
		this.nopreg = nopreg;
		this.templateSec = templateSec;
	}

	public int getQidDetalle() {
		return this.qidDetalle;
	}

	public void setQidDetalle(int qidDetalle) {
		this.qidDetalle = qidDetalle;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public Integer getSsid() {
		return this.ssid;
	}

	public void setSsid(Integer ssid) {
		this.ssid = ssid;
	}

	public String getNopreg() {
		return this.nopreg;
	}

	public void setNopreg(String nopreg) {
		this.nopreg = nopreg;
	}

	public String getTemplateSec() {
		return this.templateSec;
	}

	public void setTemplateSec(String templateSec) {
		this.templateSec = templateSec;
	}

}
