package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

/**
 * QuestionsDependenceId generated by hbm2java
 */
public class QuestionsDependenceId implements java.io.Serializable {

	private int qid;
	private int labelId;

	public QuestionsDependenceId() {
	}

	public QuestionsDependenceId(int qid, int labelId) {
		this.qid = qid;
		this.labelId = labelId;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public int getLabelId() {
		return this.labelId;
	}

	public void setLabelId(int labelId) {
		this.labelId = labelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestionsDependenceId))
			return false;
		QuestionsDependenceId castOther = (QuestionsDependenceId) other;

		return (this.getQid() == castOther.getQid())
				&& (this.getLabelId() == castOther.getLabelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getQid();
		result = 37 * result + this.getLabelId();
		return result;
	}

}
