package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	private Integer qid;
	private int version;
	private CatState catState;
	private String question;
	private String qidKey;
	private Set<SurveyQuestionDependency> surveyQuestionDependencies = new HashSet<SurveyQuestionDependency>(
			0);
	private Set<SurveyDetail> surveyDetails = new HashSet<SurveyDetail>(0);
	private Set<QuestionsRelations> questionsRelationses = new HashSet<QuestionsRelations>(
			0);
	private Set<QuestionValidation> questionValidations = new HashSet<QuestionValidation>(
			0);
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);
	private Set<QuestionsAnswers> questionsAnswerses = new HashSet<QuestionsAnswers>(
			0);
	private Set<QuestionsDependence> questionsDependences = new HashSet<QuestionsDependence>(
			0);

	public Questions() {
	}

	public Questions(CatState catState) {
		this.catState = catState;
	}

	public Questions(CatState catState, String question, String qidKey,
			Set<SurveyQuestionDependency> surveyQuestionDependencies,
			Set<SurveyDetail> surveyDetails,
			Set<QuestionsRelations> questionsRelationses,
			Set<QuestionValidation> questionValidations,
			Set<SurveyResult> surveyResults,
			Set<QuestionsAnswers> questionsAnswerses,
			Set<QuestionsDependence> questionsDependences) {
		this.catState = catState;
		this.question = question;
		this.qidKey = qidKey;
		this.surveyQuestionDependencies = surveyQuestionDependencies;
		this.surveyDetails = surveyDetails;
		this.questionsRelationses = questionsRelationses;
		this.questionValidations = questionValidations;
		this.surveyResults = surveyResults;
		this.questionsAnswerses = questionsAnswerses;
		this.questionsDependences = questionsDependences;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public CatState getCatState() {
		return this.catState;
	}

	public void setCatState(CatState catState) {
		this.catState = catState;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getQidKey() {
		return this.qidKey;
	}

	public void setQidKey(String qidKey) {
		this.qidKey = qidKey;
	}

	public Set<SurveyQuestionDependency> getSurveyQuestionDependencies() {
		return this.surveyQuestionDependencies;
	}

	public void setSurveyQuestionDependencies(
			Set<SurveyQuestionDependency> surveyQuestionDependencies) {
		this.surveyQuestionDependencies = surveyQuestionDependencies;
	}

	public Set<SurveyDetail> getSurveyDetails() {
		return this.surveyDetails;
	}

	public void setSurveyDetails(Set<SurveyDetail> surveyDetails) {
		this.surveyDetails = surveyDetails;
	}

	public Set<QuestionsRelations> getQuestionsRelationses() {
		return this.questionsRelationses;
	}

	public void setQuestionsRelationses(
			Set<QuestionsRelations> questionsRelationses) {
		this.questionsRelationses = questionsRelationses;
	}

	public Set<QuestionValidation> getQuestionValidations() {
		return this.questionValidations;
	}

	public void setQuestionValidations(
			Set<QuestionValidation> questionValidations) {
		this.questionValidations = questionValidations;
	}

	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

	public Set<QuestionsAnswers> getQuestionsAnswerses() {
		return this.questionsAnswerses;
	}

	public void setQuestionsAnswerses(Set<QuestionsAnswers> questionsAnswerses) {
		this.questionsAnswerses = questionsAnswerses;
	}

	public Set<QuestionsDependence> getQuestionsDependences() {
		return this.questionsDependences;
	}

	public void setQuestionsDependences(
			Set<QuestionsDependence> questionsDependences) {
		this.questionsDependences = questionsDependences;
	}

}
