package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * QuestionsRelations generated by hbm2java
 */
public class QuestionsRelations implements java.io.Serializable {

	private QuestionsRelationsId id;
	private Date fechaRelacion;
	private int idQColection;

	public QuestionsRelations() {
	}

	public QuestionsRelations(QuestionsRelationsId id, Date fechaRelacion,
			int idQColection) {
		this.id = id;
		this.fechaRelacion = fechaRelacion;
		this.idQColection = idQColection;
	}

	public QuestionsRelationsId getId() {
		return this.id;
	}

	public void setId(QuestionsRelationsId id) {
		this.id = id;
	}

	public Date getFechaRelacion() {
		return this.fechaRelacion;
	}

	public void setFechaRelacion(Date fechaRelacion) {
		this.fechaRelacion = fechaRelacion;
	}

	public int getIdQColection() {
		return this.idQColection;
	}

	public void setIdQColection(int idQColection) {
		this.idQColection = idQColection;
	}

}
