package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * QuestionColettion generated by hbm2java
 */
public class QuestionColettion implements java.io.Serializable {

	private Integer idQColection;
	private SecUsers secUsers;
	private String desColeccion;
	private Date creationDate;
	private Set<QuestionsRelations> questionsRelationses = new HashSet<QuestionsRelations>(
			0);

	public QuestionColettion() {
	}

	public QuestionColettion(SecUsers secUsers, String desColeccion,
			Date creationDate) {
		this.secUsers = secUsers;
		this.desColeccion = desColeccion;
		this.creationDate = creationDate;
	}

	public QuestionColettion(SecUsers secUsers, String desColeccion,
			Date creationDate, Set<QuestionsRelations> questionsRelationses) {
		this.secUsers = secUsers;
		this.desColeccion = desColeccion;
		this.creationDate = creationDate;
		this.questionsRelationses = questionsRelationses;
	}

	public Integer getIdQColection() {
		return this.idQColection;
	}

	public void setIdQColection(Integer idQColection) {
		this.idQColection = idQColection;
	}

	public SecUsers getSecUsers() {
		return this.secUsers;
	}

	public void setSecUsers(SecUsers secUsers) {
		this.secUsers = secUsers;
	}

	public String getDesColeccion() {
		return this.desColeccion;
	}

	public void setDesColeccion(String desColeccion) {
		this.desColeccion = desColeccion;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Set<QuestionsRelations> getQuestionsRelationses() {
		return this.questionsRelationses;
	}

	public void setQuestionsRelationses(
			Set<QuestionsRelations> questionsRelationses) {
		this.questionsRelationses = questionsRelationses;
	}

}
