package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * QuestionsRelationsId generated by hbm2java
 */
public class QuestionsRelationsId implements java.io.Serializable {

	private int idQidRel;
	private int qid;

	public QuestionsRelationsId() {
	}

	public QuestionsRelationsId(int idQidRel, int qid) {
		this.idQidRel = idQidRel;
		this.qid = qid;
	}

	public int getIdQidRel() {
		return this.idQidRel;
	}

	public void setIdQidRel(int idQidRel) {
		this.idQidRel = idQidRel;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuestionsRelationsId))
			return false;
		QuestionsRelationsId castOther = (QuestionsRelationsId) other;

		return (this.getIdQidRel() == castOther.getIdQidRel())
				&& (this.getQid() == castOther.getQid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdQidRel();
		result = 37 * result + this.getQid();
		return result;
	}

}
