package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * QuestionsLabels generated by hbm2java
 */
public class QuestionsLabels implements java.io.Serializable {

	private int labelId;
	private String name;
	private Integer labelOrder;
	private Set<QuestionsDependence> questionsDependences = new HashSet<QuestionsDependence>(
			0);

	public QuestionsLabels() {
	}

	public QuestionsLabels(int labelId) {
		this.labelId = labelId;
	}

	public QuestionsLabels(int labelId, String name, Integer labelOrder,
			Set<QuestionsDependence> questionsDependences) {
		this.labelId = labelId;
		this.name = name;
		this.labelOrder = labelOrder;
		this.questionsDependences = questionsDependences;
	}

	public int getLabelId() {
		return this.labelId;
	}

	public void setLabelId(int labelId) {
		this.labelId = labelId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLabelOrder() {
		return this.labelOrder;
	}

	public void setLabelOrder(Integer labelOrder) {
		this.labelOrder = labelOrder;
	}

	public Set<QuestionsDependence> getQuestionsDependences() {
		return this.questionsDependences;
	}

	public void setQuestionsDependences(
			Set<QuestionsDependence> questionsDependences) {
		this.questionsDependences = questionsDependences;
	}

}
