package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * QuestionsAnswers generated by hbm2java
 */
public class QuestionsAnswers implements java.io.Serializable {

	private QuestionsAnswersId id;

	public QuestionsAnswers() {
	}

	public QuestionsAnswers(QuestionsAnswersId id) {
		this.id = id;
	}

	public QuestionsAnswersId getId() {
		return this.id;
	}

	public void setId(QuestionsAnswersId id) {
		this.id = id;
	}

}
