package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	private Integer qid;
	private int version;
	private CatState catState;
	private String question;
	private String qidKey;
	private Set<QuestionsRelations> questionsRelationses = new HashSet<QuestionsRelations>(
			0);
	private Set<SurveyDetail> surveyDetails = new HashSet<SurveyDetail>(0);
	private Set<QuestionsAnswers> questionsAnswerses = new HashSet<QuestionsAnswers>(
			0);

	public Questions() {
	}

	public Questions(CatState catState) {
		this.catState = catState;
	}

	public Questions(CatState catState, String question, String qidKey,
			Set<QuestionsRelations> questionsRelationses,
			Set<SurveyDetail> surveyDetails,
			Set<QuestionsAnswers> questionsAnswerses) {
		this.catState = catState;
		this.question = question;
		this.qidKey = qidKey;
		this.questionsRelationses = questionsRelationses;
		this.surveyDetails = surveyDetails;
		this.questionsAnswerses = questionsAnswerses;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public CatState getCatState() {
		return this.catState;
	}

	public void setCatState(CatState catState) {
		this.catState = catState;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getQidKey() {
		return this.qidKey;
	}

	public void setQidKey(String qidKey) {
		this.qidKey = qidKey;
	}

	public Set<QuestionsRelations> getQuestionsRelationses() {
		return this.questionsRelationses;
	}

	public void setQuestionsRelationses(
			Set<QuestionsRelations> questionsRelationses) {
		this.questionsRelationses = questionsRelationses;
	}

	public Set<SurveyDetail> getSurveyDetails() {
		return this.surveyDetails;
	}

	public void setSurveyDetails(Set<SurveyDetail> surveyDetails) {
		this.surveyDetails = surveyDetails;
	}

	public Set<QuestionsAnswers> getQuestionsAnswerses() {
		return this.questionsAnswerses;
	}

	public void setQuestionsAnswerses(Set<QuestionsAnswers> questionsAnswerses) {
		this.questionsAnswerses = questionsAnswerses;
	}

}
