package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	private Integer qid;
	private int version;
	private String question;
	private int idState;
	private String qidKey;

	public Questions() {
	}

	public Questions(int idState) {
		this.idState = idState;
	}

	public Questions(String question, int idState, String qidKey) {
		this.question = question;
		this.idState = idState;
		this.qidKey = qidKey;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public String getQidKey() {
		return this.qidKey;
	}

	public void setQidKey(String qidKey) {
		this.qidKey = qidKey;
	}

}
