package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * QuestionsDependence generated by hbm2java
 */
public class QuestionsDependence implements java.io.Serializable {

	private QuestionsDependenceId id;
	private QuestionsLabels questionsLabels;
	private Questions questions;
	private String conditional;
	private Integer dependenceStart;
	private Integer dependenceFinalize;

	public QuestionsDependence() {
	}

	public QuestionsDependence(QuestionsDependenceId id,
			QuestionsLabels questionsLabels, Questions questions) {
		this.id = id;
		this.questionsLabels = questionsLabels;
		this.questions = questions;
	}

	public QuestionsDependence(QuestionsDependenceId id,
			QuestionsLabels questionsLabels, Questions questions,
			String conditional, Integer dependenceStart,
			Integer dependenceFinalize) {
		this.id = id;
		this.questionsLabels = questionsLabels;
		this.questions = questions;
		this.conditional = conditional;
		this.dependenceStart = dependenceStart;
		this.dependenceFinalize = dependenceFinalize;
	}

	public QuestionsDependenceId getId() {
		return this.id;
	}

	public void setId(QuestionsDependenceId id) {
		this.id = id;
	}

	public QuestionsLabels getQuestionsLabels() {
		return this.questionsLabels;
	}

	public void setQuestionsLabels(QuestionsLabels questionsLabels) {
		this.questionsLabels = questionsLabels;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public String getConditional() {
		return this.conditional;
	}

	public void setConditional(String conditional) {
		this.conditional = conditional;
	}

	public Integer getDependenceStart() {
		return this.dependenceStart;
	}

	public void setDependenceStart(Integer dependenceStart) {
		this.dependenceStart = dependenceStart;
	}

	public Integer getDependenceFinalize() {
		return this.dependenceFinalize;
	}

	public void setDependenceFinalize(Integer dependenceFinalize) {
		this.dependenceFinalize = dependenceFinalize;
	}

}
