package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

/**
 * QuestionsAnswers generated by hbm2java
 */
public class QuestionsAnswers implements java.io.Serializable {

	private QuestionsAnswersId id;
	private Questions questions;
	private String answer;

	public QuestionsAnswers() {
	}

	public QuestionsAnswers(QuestionsAnswersId id, Questions questions) {
		this.id = id;
		this.questions = questions;
	}

	public QuestionsAnswers(QuestionsAnswersId id, Questions questions,
			String answer) {
		this.id = id;
		this.questions = questions;
		this.answer = answer;
	}

	public QuestionsAnswersId getId() {
		return this.id;
	}

	public void setId(QuestionsAnswersId id) {
		this.id = id;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
