package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * QuestionValidation generated by hbm2java
 */
public class QuestionValidation implements java.io.Serializable {

	private Integer idValidation;
	private Integer qid;
	private Integer idTypeVal;
	private String parametros;

	public QuestionValidation() {
	}

	public QuestionValidation(Integer qid, Integer idTypeVal, String parametros) {
		this.qid = qid;
		this.idTypeVal = idTypeVal;
		this.parametros = parametros;
	}

	public Integer getIdValidation() {
		return this.idValidation;
	}

	public void setIdValidation(Integer idValidation) {
		this.idValidation = idValidation;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public Integer getIdTypeVal() {
		return this.idTypeVal;
	}

	public void setIdTypeVal(Integer idTypeVal) {
		this.idTypeVal = idTypeVal;
	}

	public String getParametros() {
		return this.parametros;
	}

	public void setParametros(String parametros) {
		this.parametros = parametros;
	}

}
