package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ResultSurveyNivel2 generated by hbm2java
 */
public class ResultSurveyNivel2 implements java.io.Serializable {

	private ResultSurveyNivel2Id id;
	private String label;
	private String respn2;

	public ResultSurveyNivel2() {
	}

	public ResultSurveyNivel2(ResultSurveyNivel2Id id, String label,
			String respn2) {
		this.id = id;
		this.label = label;
		this.respn2 = respn2;
	}

	public ResultSurveyNivel2Id getId() {
		return this.id;
	}

	public void setId(ResultSurveyNivel2Id id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getRespn2() {
		return this.respn2;
	}

	public void setRespn2(String respn2) {
		this.respn2 = respn2;
	}

}
