package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SecBannedips generated by hbm2java
 */
public class SecBannedips implements java.io.Serializable {

	private Integer id;
	private String ip;
	private String reason;

	public SecBannedips() {
	}

	public SecBannedips(String ip, String reason) {
		this.ip = ip;
		this.reason = reason;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
