package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecGroups generated by hbm2java
 */
public class SecGroups implements java.io.Serializable {

	private Integer groupId;
	private String name;
	private String desInfo;
	private int idState;
	private Set<SecGroupUser> secGroupUsers = new HashSet<SecGroupUser>(0);
	private Set<ProjectGroup> proyectGroups = new HashSet<ProjectGroup>(0);
	private Set<SecGroupPermission> secGroupPermissions = new HashSet<SecGroupPermission>(
			0);

	public SecGroups() {
	}

	public SecGroups(int idState) {
		this.idState = idState;
	}

	public SecGroups(String name, String desInfo, int idState,
			Set<SecGroupUser> secGroupUsers, Set<ProjectGroup> proyectGroups,
			Set<SecGroupPermission> secGroupPermissions) {
		this.name = name;
		this.desInfo = desInfo;
		this.idState = idState;
		this.secGroupUsers = secGroupUsers;
		this.proyectGroups = proyectGroups;
		this.secGroupPermissions = secGroupPermissions;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesInfo() {
		return this.desInfo;
	}

	public void setDesInfo(String desInfo) {
		this.desInfo = desInfo;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public Set<SecGroupUser> getSecGroupUsers() {
		return this.secGroupUsers;
	}

	public void setSecGroupUsers(Set<SecGroupUser> secGroupUsers) {
		this.secGroupUsers = secGroupUsers;
	}

	public Set<ProjectGroup> getProyectGroups() {
		return this.proyectGroups;
	}

	public void setProyectGroups(Set<ProjectGroup> proyectGroups) {
		this.proyectGroups = proyectGroups;
	}

	public Set<SecGroupPermission> getSecGroupPermissions() {
		return this.secGroupPermissions;
	}

	public void setSecGroupPermissions(
			Set<SecGroupPermission> secGroupPermissions) {
		this.secGroupPermissions = secGroupPermissions;
	}

}
