package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecGroups generated by hbm2java
 */
public class SecGroups implements java.io.Serializable {

	private Integer groupId;
	private String name;
	private String desInfo;
	private int idState;
	private Set<SecGroupUser> secGroupUsers = new HashSet<SecGroupUser>(0);
	private Set<SecGroupPermission> secGroupPermissions = new HashSet<SecGroupPermission>(
			0);
	private Set<ProjectGroup> projectGroups = new HashSet<ProjectGroup>(0);
	private Set<ProjectLocation> projectLocations = new HashSet<ProjectLocation>(
			0);

	public SecGroups() {
	}

	public SecGroups(int idState) {
		this.idState = idState;
	}

	public SecGroups(String name, String desInfo, int idState,
			Set<SecGroupUser> secGroupUsers,
			Set<SecGroupPermission> secGroupPermissions,
			Set<ProjectGroup> projectGroups,
			Set<ProjectLocation> projectLocations) {
		this.name = name;
		this.desInfo = desInfo;
		this.idState = idState;
		this.secGroupUsers = secGroupUsers;
		this.secGroupPermissions = secGroupPermissions;
		this.projectGroups = projectGroups;
		this.projectLocations = projectLocations;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesInfo() {
		return this.desInfo;
	}

	public void setDesInfo(String desInfo) {
		this.desInfo = desInfo;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public Set<SecGroupUser> getSecGroupUsers() {
		return this.secGroupUsers;
	}

	public void setSecGroupUsers(Set<SecGroupUser> secGroupUsers) {
		this.secGroupUsers = secGroupUsers;
	}

	public Set<SecGroupPermission> getSecGroupPermissions() {
		return this.secGroupPermissions;
	}

	public void setSecGroupPermissions(
			Set<SecGroupPermission> secGroupPermissions) {
		this.secGroupPermissions = secGroupPermissions;
	}

	public Set<ProjectGroup> getProjectGroups() {
		return this.projectGroups;
	}

	public void setProjectGroups(Set<ProjectGroup> projectGroups) {
		this.projectGroups = projectGroups;
	}

	public Set<ProjectLocation> getProjectLocations() {
		return this.projectLocations;
	}

	public void setProjectLocations(Set<ProjectLocation> projectLocations) {
		this.projectLocations = projectLocations;
	}

}
