package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * SecInvite generated by hbm2java
 */
public class SecInvite implements java.io.Serializable {

	private String code;
	private String email;
	private Date createdOn;

	public SecInvite() {
	}

	public SecInvite(String code, String email, Date createdOn) {
		this.code = code;
		this.email = email;
		this.createdOn = createdOn;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

}
