package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SecPermission generated by hbm2java
 */
public class SecPermission implements java.io.Serializable {

	private int idPermission;
	private String permission;
	private String description;
	private Set<SecGroupPermission> secGroupPermissions = new HashSet<SecGroupPermission>(
			0);

	public SecPermission() {
	}

	public SecPermission(int idPermission) {
		this.idPermission = idPermission;
	}

	public SecPermission(int idPermission, String permission,
			String description, Set<SecGroupPermission> secGroupPermissions) {
		this.idPermission = idPermission;
		this.permission = permission;
		this.description = description;
		this.secGroupPermissions = secGroupPermissions;
	}

	public int getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(int idPermission) {
		this.idPermission = idPermission;
	}

	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<SecGroupPermission> getSecGroupPermissions() {
		return this.secGroupPermissions;
	}

	public void setSecGroupPermissions(
			Set<SecGroupPermission> secGroupPermissions) {
		this.secGroupPermissions = secGroupPermissions;
	}

}
