package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SecUsers generated by hbm2java
 */
public class SecUsers implements java.io.Serializable {

	private Integer uid;
	private CatState catState;
	private String sex;
	private String name;
	private String email;
	private String username;
	private String password;
	private String passwordClean;
	private Integer birthDate;
	private String address;
	private String nocId;
	private Boolean status;
	private String inviteCode;
	private String position;
	private Date dateNew;
	private String publisher;
	private Set<ProyectUser> proyectUsers = new HashSet<ProyectUser>(0);
	private Set<SecGroupUser> secGroupUsers = new HashSet<SecGroupUser>(0);
	private Set<SecUserPermission> secUserPermissions = new HashSet<SecUserPermission>(
			0);
	private Set<CatLocationUser> catLocationUsers = new HashSet<CatLocationUser>(
			0);
	private Set<SurveyResultMod> surveyResultMods = new HashSet<SurveyResultMod>(
			0);
	private Set<QuestionColettion> questionColettions = new HashSet<QuestionColettion>(
			0);
	private Set<Surveys> surveyses = new HashSet<Surveys>(0);

	public SecUsers() {
	}

	public SecUsers(CatState catState, String name, String email,
			String password, boolean status, Date dateNew, String publisher) {
		this.catState = catState;
		this.name = name;
		this.email = email;
		this.password = password;
		this.status = status;
		this.dateNew = dateNew;
		this.publisher = publisher;
	}

	public SecUsers(CatState catState, String sex, String name, String email,
			String username, String password, String passwordClean,
			Integer birthDate, String address, String nocId, boolean status,
			String inviteCode, String position, Date dateNew, String publisher,
			Set<ProyectUser> proyectUsers, Set<SecGroupUser> secGroupUsers,
			Set<SecUserPermission> secUserPermissions,
			Set<CatLocationUser> catLocationUsers,
			Set<SurveyResultMod> surveyResultMods,
			Set<QuestionColettion> questionColettions, Set<Surveys> surveyses) {
		this.catState = catState;
		this.sex = sex;
		this.name = name;
		this.email = email;
		this.username = username;
		this.password = password;
		this.passwordClean = passwordClean;
		this.birthDate = birthDate;
		this.address = address;
		this.nocId = nocId;
		this.status = status;
		this.inviteCode = inviteCode;
		this.position = position;
		this.dateNew = dateNew;
		this.publisher = publisher;
		this.proyectUsers = proyectUsers;
		this.secGroupUsers = secGroupUsers;
		this.secUserPermissions = secUserPermissions;
		this.catLocationUsers = catLocationUsers;
		this.surveyResultMods = surveyResultMods;
		this.questionColettions = questionColettions;
		this.surveyses = surveyses;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public CatState getCatState() {
		return this.catState;
	}

	public void setCatState(CatState catState) {
		this.catState = catState;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordClean() {
		return this.passwordClean;
	}

	public void setPasswordClean(String passwordClean) {
		this.passwordClean = passwordClean;
	}

	public Integer getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Integer birthDate) {
		this.birthDate = birthDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNocId() {
		return this.nocId;
	}

	public void setNocId(String nocId) {
		this.nocId = nocId;
	}

	public Boolean isStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getInviteCode() {
		return this.inviteCode;
	}

	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Date getDateNew() {
		return this.dateNew;
	}

	public void setDateNew(Date dateNew) {
		this.dateNew = dateNew;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Set<ProyectUser> getProyectUsers() {
		return this.proyectUsers;
	}

	public void setProyectUsers(Set<ProyectUser> proyectUsers) {
		this.proyectUsers = proyectUsers;
	}

	public Set<SecGroupUser> getSecGroupUsers() {
		return this.secGroupUsers;
	}

	public void setSecGroupUsers(Set<SecGroupUser> secGroupUsers) {
		this.secGroupUsers = secGroupUsers;
	}

	public Set<SecUserPermission> getSecUserPermissions() {
		return this.secUserPermissions;
	}

	public void setSecUserPermissions(Set<SecUserPermission> secUserPermissions) {
		this.secUserPermissions = secUserPermissions;
	}

	public Set<CatLocationUser> getCatLocationUsers() {
		return this.catLocationUsers;
	}

	public void setCatLocationUsers(Set<CatLocationUser> catLocationUsers) {
		this.catLocationUsers = catLocationUsers;
	}

	public Set<SurveyResultMod> getSurveyResultMods() {
		return this.surveyResultMods;
	}

	public void setSurveyResultMods(Set<SurveyResultMod> surveyResultMods) {
		this.surveyResultMods = surveyResultMods;
	}

	public Set<QuestionColettion> getQuestionColettions() {
		return this.questionColettions;
	}

	public void setQuestionColettions(Set<QuestionColettion> questionColettions) {
		this.questionColettions = questionColettions;
	}

	public Set<Surveys> getSurveyses() {
		return this.surveyses;
	}

	public void setSurveyses(Set<Surveys> surveyses) {
		this.surveyses = surveyses;
	}

}
