package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * SecUserPermissionId generated by hbm2java
 */
public class SecUserPermissionId implements java.io.Serializable {

	private int uid;
	private int idPermission;

	public SecUserPermissionId() {
	}

	public SecUserPermissionId(int uid, int idPermission) {
		this.uid = uid;
		this.idPermission = idPermission;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(int idPermission) {
		this.idPermission = idPermission;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecUserPermissionId))
			return false;
		SecUserPermissionId castOther = (SecUserPermissionId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getIdPermission() == castOther.getIdPermission());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getIdPermission();
		return result;
	}

}
