package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SecUserPermission generated by hbm2java
 */
public class SecUserPermission implements java.io.Serializable {

	private SecUserPermissionId id;
	private SecPermission secPermission;
	private SecUsers secUsers;
	private Boolean state;

	public SecUserPermission() {
	}

	public SecUserPermission(SecUserPermissionId id,
			SecPermission secPermission, SecUsers secUsers) {
		this.id = id;
		this.secPermission = secPermission;
		this.secUsers = secUsers;
	}

	public SecUserPermission(SecUserPermissionId id,
			SecPermission secPermission, SecUsers secUsers, Boolean state) {
		this.id = id;
		this.secPermission = secPermission;
		this.secUsers = secUsers;
		this.state = state;
	}

	public SecUserPermissionId getId() {
		return this.id;
	}

	public void setId(SecUserPermissionId id) {
		this.id = id;
	}

	public SecPermission getSecPermission() {
		return this.secPermission;
	}

	public void setSecPermission(SecPermission secPermission) {
		this.secPermission = secPermission;
	}

	public SecUsers getSecUsers() {
		return this.secUsers;
	}

	public void setSecUsers(SecUsers secUsers) {
		this.secUsers = secUsers;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

}
