package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SurveyLocationId generated by hbm2java
 */
public class SurveyLocationId implements java.io.Serializable {

	private int stid;
	private int siteid;
	private int tid;

	public SurveyLocationId() {
	}

	public SurveyLocationId(int stid, int siteid, int tid) {
		this.stid = stid;
		this.siteid = siteid;
		this.tid = tid;
	}

	public int getStid() {
		return this.stid;
	}

	public void setStid(int stid) {
		this.stid = stid;
	}

	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SurveyLocationId))
			return false;
		SurveyLocationId castOther = (SurveyLocationId) other;

		return (this.getStid() == castOther.getStid())
				&& (this.getSiteid() == castOther.getSiteid())
				&& (this.getTid() == castOther.getTid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStid();
		result = 37 * result + this.getSiteid();
		result = 37 * result + this.getTid();
		return result;
	}

}
