package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SurveyGroup generated by hbm2java
 */
public class SurveyGroup implements java.io.Serializable {

	private int sgId;
	private Integer version;
	private String groupName;
	private Date dateCreate;
	private Integer idState;
	private int idSidFormat;
	private Set<SurveyFormatGroup> surveyFormatGroups = new HashSet<SurveyFormatGroup>(
			0);
	private Set<SurveyGroupProject> surveyGroupProjects = new HashSet<SurveyGroupProject>(
			0);

	public SurveyGroup() {
	}

	public SurveyGroup(int sgId, int idSidFormat) {
		this.sgId = sgId;
		this.idSidFormat = idSidFormat;
	}

	public SurveyGroup(int sgId, String groupName, Date dateCreate,
			Integer idState, int idSidFormat,
			Set<SurveyFormatGroup> surveyFormatGroups,
			Set<SurveyGroupProject> surveyGroupProjects) {
		this.sgId = sgId;
		this.groupName = groupName;
		this.dateCreate = dateCreate;
		this.idState = idState;
		this.idSidFormat = idSidFormat;
		this.surveyFormatGroups = surveyFormatGroups;
		this.surveyGroupProjects = surveyGroupProjects;
	}

	public int getSgId() {
		return this.sgId;
	}

	public void setSgId(int sgId) {
		this.sgId = sgId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	public int getIdSidFormat() {
		return this.idSidFormat;
	}

	public void setIdSidFormat(int idSidFormat) {
		this.idSidFormat = idSidFormat;
	}

	public Set<SurveyFormatGroup> getSurveyFormatGroups() {
		return this.surveyFormatGroups;
	}

	public void setSurveyFormatGroups(Set<SurveyFormatGroup> surveyFormatGroups) {
		this.surveyFormatGroups = surveyFormatGroups;
	}

	public Set<SurveyGroupProject> getSurveyGroupProjects() {
		return this.surveyGroupProjects;
	}

	public void setSurveyGroupProjects(
			Set<SurveyGroupProject> surveyGroupProjects) {
		this.surveyGroupProjects = surveyGroupProjects;
	}

}
