package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SurveySection generated by hbm2java
 */
public class SurveySection implements java.io.Serializable {

	private Integer ssid;
	private int version;
	private CatLocation catLocation;
	private String descSection;
	private int level;
	private String template;
	private Set<SurveyQuestionDependency> surveyQuestionDependencies = new HashSet<SurveyQuestionDependency>(
			0);
	private Set<SurveyDetail> surveyDetails = new HashSet<SurveyDetail>(0);
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);
	private Set<SurveySectionType> surveySectionTypes = new HashSet<SurveySectionType>(
			0);

	public SurveySection() {
	}

	public SurveySection(CatLocation catLocation, int level, String template) {
		this.catLocation = catLocation;
		this.level = level;
		this.template = template;
	}

	public SurveySection(CatLocation catLocation, String descSection,
			int level, String template,
			Set<SurveyQuestionDependency> surveyQuestionDependencies,
			Set<SurveyDetail> surveyDetails, Set<SurveyResult> surveyResults,
			Set<SurveySectionType> surveySectionTypes) {
		this.catLocation = catLocation;
		this.descSection = descSection;
		this.level = level;
		this.template = template;
		this.surveyQuestionDependencies = surveyQuestionDependencies;
		this.surveyDetails = surveyDetails;
		this.surveyResults = surveyResults;
		this.surveySectionTypes = surveySectionTypes;
	}

	public Integer getSsid() {
		return this.ssid;
	}

	public void setSsid(Integer ssid) {
		this.ssid = ssid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public CatLocation getCatLocation() {
		return this.catLocation;
	}

	public void setCatLocation(CatLocation catLocation) {
		this.catLocation = catLocation;
	}

	public String getDescSection() {
		return this.descSection;
	}

	public void setDescSection(String descSection) {
		this.descSection = descSection;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public Set<SurveyQuestionDependency> getSurveyQuestionDependencies() {
		return this.surveyQuestionDependencies;
	}

	public void setSurveyQuestionDependencies(
			Set<SurveyQuestionDependency> surveyQuestionDependencies) {
		this.surveyQuestionDependencies = surveyQuestionDependencies;
	}

	public Set<SurveyDetail> getSurveyDetails() {
		return this.surveyDetails;
	}

	public void setSurveyDetails(Set<SurveyDetail> surveyDetails) {
		this.surveyDetails = surveyDetails;
	}

	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

	public Set<SurveySectionType> getSurveySectionTypes() {
		return this.surveySectionTypes;
	}

	public void setSurveySectionTypes(Set<SurveySectionType> surveySectionTypes) {
		this.surveySectionTypes = surveySectionTypes;
	}

}
