package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

/**
 * SurveyLocationId generated by hbm2java
 */
public class SurveyLocationId implements java.io.Serializable {

	private int stid;
	private int proyectId;
	private int tid;

	public SurveyLocationId() {
	}

	public SurveyLocationId(int stid, int proyectId, int tid) {
		this.stid = stid;
		this.proyectId = proyectId;
		this.tid = tid;
	}

	public int getStid() {
		return this.stid;
	}

	public void setStid(int stid) {
		this.stid = stid;
	}

	public int getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(int proyectId) {
		this.proyectId = proyectId;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SurveyLocationId))
			return false;
		SurveyLocationId castOther = (SurveyLocationId) other;

		return (this.getStid() == castOther.getStid())
				&& (this.getProyectId() == castOther.getProyectId())
				&& (this.getTid() == castOther.getTid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStid();
		result = 37 * result + this.getProyectId();
		result = 37 * result + this.getTid();
		return result;
	}

}
