package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SurveySection generated by hbm2java
 */
public class SurveySection implements java.io.Serializable {

	private Integer ssid;
	private int version;
	private String descSection;
	private int level;
	private String template;
	private int idState;

	public SurveySection() {
	}

	public SurveySection(int level, String template, int idState) {
		this.level = level;
		this.template = template;
		this.idState = idState;
	}

	public SurveySection(String descSection, int level, String template,
			int idState) {
		this.descSection = descSection;
		this.level = level;
		this.template = template;
		this.idState = idState;
	}

	public Integer getSsid() {
		return this.ssid;
	}

	public void setSsid(Integer ssid) {
		this.ssid = ssid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getDescSection() {
		return this.descSection;
	}

	public void setDescSection(String descSection) {
		this.descSection = descSection;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

}
