package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

/**
 * SurveyLocation generated by hbm2java
 */
public class SurveyLocation implements java.io.Serializable {

	private SurveyLocationId id;
	private Proyect proyect;
	private CatLocation catLocation;
	private int from;
	private int to;
	private Integer captured;
	private Integer reported;

	public SurveyLocation() {
	}

	public SurveyLocation(SurveyLocationId id, Proyect proyect,
			CatLocation catLocation, int from, int to) {
		this.id = id;
		this.proyect = proyect;
		this.catLocation = catLocation;
		this.from = from;
		this.to = to;
	}

	public SurveyLocation(SurveyLocationId id, Proyect proyect,
			CatLocation catLocation, int from, int to, Integer captured,
			Integer reported) {
		this.id = id;
		this.proyect = proyect;
		this.catLocation = catLocation;
		this.from = from;
		this.to = to;
		this.captured = captured;
		this.reported = reported;
	}

	public SurveyLocationId getId() {
		return this.id;
	}

	public void setId(SurveyLocationId id) {
		this.id = id;
	}

	public Proyect getProyect() {
		return this.proyect;
	}

	public void setProyect(Proyect proyect) {
		this.proyect = proyect;
	}

	public CatLocation getCatLocation() {
		return this.catLocation;
	}

	public void setCatLocation(CatLocation catLocation) {
		this.catLocation = catLocation;
	}

	public int getFrom() {
		return this.from;
	}

	public void setFrom(int from) {
		this.from = from;
	}

	public int getTo() {
		return this.to;
	}

	public void setTo(int to) {
		this.to = to;
	}

	public Integer getCaptured() {
		return this.captured;
	}

	public void setCaptured(Integer captured) {
		this.captured = captured;
	}

	public Integer getReported() {
		return this.reported;
	}

	public void setReported(Integer reported) {
		this.reported = reported;
	}

}
