package org.jp.core.persistence.pojo;

// Generated 27-abr-2009 18:04:46 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SurveyResult generated by hbm2java
 */
public class SurveyResult implements java.io.Serializable {

	private Long rid;
	private Surveys surveys;
	private Questions questions;
	private SurveySection surveySection;
	private String resp;
	private Set<SurveyResultMod> surveyResultMods = new HashSet<SurveyResultMod>(
			0);

	public SurveyResult() {
	}

	public SurveyResult(Surveys surveys, Questions questions,
			SurveySection surveySection, String resp) {
		this.surveys = surveys;
		this.questions = questions;
		this.surveySection = surveySection;
		this.resp = resp;
	}

	public SurveyResult(Surveys surveys, Questions questions,
			SurveySection surveySection, String resp,
			Set<SurveyResultMod> surveyResultMods) {
		this.surveys = surveys;
		this.questions = questions;
		this.surveySection = surveySection;
		this.resp = resp;
		this.surveyResultMods = surveyResultMods;
	}

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public Surveys getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Surveys surveys) {
		this.surveys = surveys;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public SurveySection getSurveySection() {
		return this.surveySection;
	}

	public void setSurveySection(SurveySection surveySection) {
		this.surveySection = surveySection;
	}

	public String getResp() {
		return this.resp;
	}

	public void setResp(String resp) {
		this.resp = resp;
	}

	public Set<SurveyResultMod> getSurveyResultMods() {
		return this.surveyResultMods;
	}

	public void setSurveyResultMods(Set<SurveyResultMod> surveyResultMods) {
		this.surveyResultMods = surveyResultMods;
	}

}
