package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SurveyDetail generated by hbm2java
 */
public class SurveyDetail implements java.io.Serializable {

	private SurveyDetailId id;
	private SurveyFormat surveyFormat;
	private Questions questions;
	private SurveySection surveySection;
	private Integer position;
	private String nopreg;

	public SurveyDetail() {
	}

	public SurveyDetail(SurveyDetailId id, SurveyFormat surveyFormat,
			Questions questions, SurveySection surveySection) {
		this.id = id;
		this.surveyFormat = surveyFormat;
		this.questions = questions;
		this.surveySection = surveySection;
	}

	public SurveyDetail(SurveyDetailId id, SurveyFormat surveyFormat,
			Questions questions, SurveySection surveySection, Integer position,
			String nopreg) {
		this.id = id;
		this.surveyFormat = surveyFormat;
		this.questions = questions;
		this.surveySection = surveySection;
		this.position = position;
		this.nopreg = nopreg;
	}

	public SurveyDetailId getId() {
		return this.id;
	}

	public void setId(SurveyDetailId id) {
		this.id = id;
	}

	public SurveyFormat getSurveyFormat() {
		return this.surveyFormat;
	}

	public void setSurveyFormat(SurveyFormat surveyFormat) {
		this.surveyFormat = surveyFormat;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public SurveySection getSurveySection() {
		return this.surveySection;
	}

	public void setSurveySection(SurveySection surveySection) {
		this.surveySection = surveySection;
	}

	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	public String getNopreg() {
		return this.nopreg;
	}

	public void setNopreg(String nopreg) {
		this.nopreg = nopreg;
	}

}
