package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * SurveyDetail generated by hbm2java
 */
public class SurveyDetail implements java.io.Serializable {

	private SurveyDetailId id;
	private QuestionsPatron questionsPatron;
	private SurveyType surveyType;
	private Questions questions;
	private SurveySection surveySection;
	private Integer position;
	private float noquestion;
	private String template;

	public SurveyDetail() {
	}

	public SurveyDetail(SurveyDetailId id, SurveyType surveyType,
			Questions questions, SurveySection surveySection, float noquestion) {
		this.id = id;
		this.surveyType = surveyType;
		this.questions = questions;
		this.surveySection = surveySection;
		this.noquestion = noquestion;
	}

	public SurveyDetail(SurveyDetailId id, QuestionsPatron questionsPatron,
			SurveyType surveyType, Questions questions,
			SurveySection surveySection, Integer position, float noquestion,
			String template) {
		this.id = id;
		this.questionsPatron = questionsPatron;
		this.surveyType = surveyType;
		this.questions = questions;
		this.surveySection = surveySection;
		this.position = position;
		this.noquestion = noquestion;
		this.template = template;
	}

	public SurveyDetailId getId() {
		return this.id;
	}

	public void setId(SurveyDetailId id) {
		this.id = id;
	}

	public QuestionsPatron getQuestionsPatron() {
		return this.questionsPatron;
	}

	public void setQuestionsPatron(QuestionsPatron questionsPatron) {
		this.questionsPatron = questionsPatron;
	}

	public SurveyType getSurveyType() {
		return this.surveyType;
	}

	public void setSurveyType(SurveyType surveyType) {
		this.surveyType = surveyType;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public SurveySection getSurveySection() {
		return this.surveySection;
	}

	public void setSurveySection(SurveySection surveySection) {
		this.surveySection = surveySection;
	}

	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	public float getNoquestion() {
		return this.noquestion;
	}

	public void setNoquestion(float noquestion) {
		this.noquestion = noquestion;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

}
