package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SurveyGroupProject generated by hbm2java
 */
public class SurveyGroupProject implements java.io.Serializable {

	private SurveyGroupProjectId id;
	private Project project;
	private SurveyGroup surveyGroup;
	private Boolean state;

	public SurveyGroupProject() {
	}

	public SurveyGroupProject(SurveyGroupProjectId id, Project project,
			SurveyGroup surveyGroup) {
		this.id = id;
		this.project = project;
		this.surveyGroup = surveyGroup;
	}

	public SurveyGroupProject(SurveyGroupProjectId id, Project project,
			SurveyGroup surveyGroup, Boolean state) {
		this.id = id;
		this.project = project;
		this.surveyGroup = surveyGroup;
		this.state = state;
	}

	public SurveyGroupProjectId getId() {
		return this.id;
	}

	public void setId(SurveyGroupProjectId id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public SurveyGroup getSurveyGroup() {
		return this.surveyGroup;
	}

	public void setSurveyGroup(SurveyGroup surveyGroup) {
		this.surveyGroup = surveyGroup;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

}
