package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * SurveySectionTypeId generated by hbm2java
 */
public class SurveySectionTypeId implements java.io.Serializable {

	private int stid;
	private int ssid;

	public SurveySectionTypeId() {
	}

	public SurveySectionTypeId(int stid, int ssid) {
		this.stid = stid;
		this.ssid = ssid;
	}

	public int getStid() {
		return this.stid;
	}

	public void setStid(int stid) {
		this.stid = stid;
	}

	public int getSsid() {
		return this.ssid;
	}

	public void setSsid(int ssid) {
		this.ssid = ssid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SurveySectionTypeId))
			return false;
		SurveySectionTypeId castOther = (SurveySectionTypeId) other;

		return (this.getStid() == castOther.getStid())
				&& (this.getSsid() == castOther.getSsid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStid();
		result = 37 * result + this.getSsid();
		return result;
	}

}
