package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SurveySection generated by hbm2java
 */
public class SurveySection implements java.io.Serializable {

	private Integer ssid;
	private CatState catState;
	private String descSection;
	private Set<SurveyDetail> surveyDetails = new HashSet<SurveyDetail>(0);

	public SurveySection() {
	}

	public SurveySection(CatState catState) {
		this.catState = catState;
	}

	public SurveySection(CatState catState, String descSection,
			Set<SurveyDetail> surveyDetails) {
		this.catState = catState;
		this.descSection = descSection;
		this.surveyDetails = surveyDetails;
	}

	public Integer getSsid() {
		return this.ssid;
	}

	public void setSsid(Integer ssid) {
		this.ssid = ssid;
	}

	public CatState getCatState() {
		return this.catState;
	}

	public void setCatState(CatState catState) {
		this.catState = catState;
	}

	public String getDescSection() {
		return this.descSection;
	}

	public void setDescSection(String descSection) {
		this.descSection = descSection;
	}

	public Set<SurveyDetail> getSurveyDetails() {
		return this.surveyDetails;
	}

	public void setSurveyDetails(Set<SurveyDetail> surveyDetails) {
		this.surveyDetails = surveyDetails;
	}

}
