package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * SurveyQuestionDependency generated by hbm2java
 */
public class SurveyQuestionDependency implements java.io.Serializable {

	private SurveyQuestionDependencyId id;
	private SurveyType surveyType;
	private Questions questions;
	private CatLocation catLocation;
	private SurveySection surveySection;
	private String patronData;
	private float patronLimit;
	private Float depHome;
	private String patronOption;
	private Integer qidLim;

	public SurveyQuestionDependency() {
	}

	public SurveyQuestionDependency(SurveyQuestionDependencyId id,
			SurveyType surveyType, Questions questions,
			CatLocation catLocation, SurveySection surveySection,
			String patronData, float patronLimit, String patronOption) {
		this.id = id;
		this.surveyType = surveyType;
		this.questions = questions;
		this.catLocation = catLocation;
		this.surveySection = surveySection;
		this.patronData = patronData;
		this.patronLimit = patronLimit;
		this.patronOption = patronOption;
	}

	public SurveyQuestionDependency(SurveyQuestionDependencyId id,
			SurveyType surveyType, Questions questions,
			CatLocation catLocation, SurveySection surveySection,
			String patronData, float patronLimit, Float depHome,
			String patronOption, Integer qidLim) {
		this.id = id;
		this.surveyType = surveyType;
		this.questions = questions;
		this.catLocation = catLocation;
		this.surveySection = surveySection;
		this.patronData = patronData;
		this.patronLimit = patronLimit;
		this.depHome = depHome;
		this.patronOption = patronOption;
		this.qidLim = qidLim;
	}

	public SurveyQuestionDependencyId getId() {
		return this.id;
	}

	public void setId(SurveyQuestionDependencyId id) {
		this.id = id;
	}

	public SurveyType getSurveyType() {
		return this.surveyType;
	}

	public void setSurveyType(SurveyType surveyType) {
		this.surveyType = surveyType;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public CatLocation getCatLocation() {
		return this.catLocation;
	}

	public void setCatLocation(CatLocation catLocation) {
		this.catLocation = catLocation;
	}

	public SurveySection getSurveySection() {
		return this.surveySection;
	}

	public void setSurveySection(SurveySection surveySection) {
		this.surveySection = surveySection;
	}

	public String getPatronData() {
		return this.patronData;
	}

	public void setPatronData(String patronData) {
		this.patronData = patronData;
	}

	public float getPatronLimit() {
		return this.patronLimit;
	}

	public void setPatronLimit(float patronLimit) {
		this.patronLimit = patronLimit;
	}

	public Float getDepHome() {
		return this.depHome;
	}

	public void setDepHome(Float depHome) {
		this.depHome = depHome;
	}

	public String getPatronOption() {
		return this.patronOption;
	}

	public void setPatronOption(String patronOption) {
		this.patronOption = patronOption;
	}

	public Integer getQidLim() {
		return this.qidLim;
	}

	public void setQidLim(Integer qidLim) {
		this.qidLim = qidLim;
	}

}
