package org.jp.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SurveyTime generated by hbm2java
 */
public class SurveyTime implements java.io.Serializable {

	private SurveyTimeId id;
	private Surveys surveys;
	private int elapsedTime;
	private int quitflag;

	public SurveyTime() {
	}

	public SurveyTime(SurveyTimeId id, Surveys surveys, int elapsedTime,
			int quitflag) {
		this.id = id;
		this.surveys = surveys;
		this.elapsedTime = elapsedTime;
		this.quitflag = quitflag;
	}

	public SurveyTimeId getId() {
		return this.id;
	}

	public void setId(SurveyTimeId id) {
		this.id = id;
	}

	public Surveys getSurveys() {
		return this.surveys;
	}

	public void setSurveys(Surveys surveys) {
		this.surveys = surveys;
	}

	public int getElapsedTime() {
		return this.elapsedTime;
	}

	public void setElapsedTime(int elapsedTime) {
		this.elapsedTime = elapsedTime;
	}

	public int getQuitflag() {
		return this.quitflag;
	}

	public void setQuitflag(int quitflag) {
		this.quitflag = quitflag;
	}

}
