package org.jp.core.persistence.pojo;

// Generated 07-may-2009 17:38:33 by Hibernate Tools 3.2.2.GA

/**
 * SurveySectionType generated by hbm2java
 */
public class SurveySectionType implements java.io.Serializable {

	private SurveySectionTypeId id;
	private SurveyType surveyType;
	private SurveySection surveySection;
	private byte state;

	public SurveySectionType() {
	}

	public SurveySectionType(SurveySectionTypeId id, SurveyType surveyType,
			SurveySection surveySection, byte state) {
		this.id = id;
		this.surveyType = surveyType;
		this.surveySection = surveySection;
		this.state = state;
	}

	public SurveySectionTypeId getId() {
		return this.id;
	}

	public void setId(SurveySectionTypeId id) {
		this.id = id;
	}

	public SurveyType getSurveyType() {
		return this.surveyType;
	}

	public void setSurveyType(SurveyType surveyType) {
		this.surveyType = surveyType;
	}

	public SurveySection getSurveySection() {
		return this.surveySection;
	}

	public void setSurveySection(SurveySection surveySection) {
		this.surveySection = surveySection;
	}

	public byte getState() {
		return this.state;
	}

	public void setState(byte state) {
		this.state = state;
	}

}
