package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * UsersSessions generated by hbm2java
 */
public class UsersSessions implements java.io.Serializable {

	private int idSession;
	private int uid;
	private String ip;
	private String session;
	private Date dateTime;
	private String start;
	private String cadenaConsulta;
	private String lenguajeCabecera;
	private String paginaReferencia;

	public UsersSessions() {
	}

	public UsersSessions(int idSession, int uid, String ip, String session) {
		this.idSession = idSession;
		this.uid = uid;
		this.ip = ip;
		this.session = session;
	}

	public UsersSessions(int idSession, int uid, String ip, String session,
			Date dateTime, String start, String cadenaConsulta,
			String lenguajeCabecera, String paginaReferencia) {
		this.idSession = idSession;
		this.uid = uid;
		this.ip = ip;
		this.session = session;
		this.dateTime = dateTime;
		this.start = start;
		this.cadenaConsulta = cadenaConsulta;
		this.lenguajeCabecera = lenguajeCabecera;
		this.paginaReferencia = paginaReferencia;
	}

	public int getIdSession() {
		return this.idSession;
	}

	public void setIdSession(int idSession) {
		this.idSession = idSession;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getSession() {
		return this.session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getCadenaConsulta() {
		return this.cadenaConsulta;
	}

	public void setCadenaConsulta(String cadenaConsulta) {
		this.cadenaConsulta = cadenaConsulta;
	}

	public String getLenguajeCabecera() {
		return this.lenguajeCabecera;
	}

	public void setLenguajeCabecera(String lenguajeCabecera) {
		this.lenguajeCabecera = lenguajeCabecera;
	}

	public String getPaginaReferencia() {
		return this.paginaReferencia;
	}

	public void setPaginaReferencia(String paginaReferencia) {
		this.paginaReferencia = paginaReferencia;
	}

}
