package org.jp.core.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Versions generated by hbm2java
 */
public class Versions implements java.io.Serializable {

	private Integer version;
	private float dataVersion;
	private Date fechaVersion;

	public Versions() {
	}

	public Versions(float dataVersion, Date fechaVersion) {
		this.dataVersion = dataVersion;
		this.fechaVersion = fechaVersion;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public float getDataVersion() {
		return this.dataVersion;
	}

	public void setDataVersion(float dataVersion) {
		this.dataVersion = dataVersion;
	}

	public Date getFechaVersion() {
		return this.fechaVersion;
	}

	public void setFechaVersion(Date fechaVersion) {
		this.fechaVersion = fechaVersion;
	}

}
