<div class="socialAccounts">

    <div class="socialWrapper">
        <div class="listSocialCommunities">
             <div id="twitter" dojoType="encuestame.org.core.commons.social.SocialButton" label="Twitter"></div>
             <div id="facebook" dojoType="encuestame.org.core.commons.social.SocialButton" label="Facebook"></div>
             <div id="linkedin" dojoType="encuestame.org.core.commons.social.SocialButton" label="Linked In"></div>
             <div id="google" dojoType="encuestame.org.core.commons.social.SocialButton" label="Google Buzz"></div>
        </div>
        <div class="socialAccountListDetail" dojoAttachPoint="_detail">
                <div>
                    INFO ACCOUNTS
                </div>
                <div id="twitterDetail" dojoType="encuestame.org.core.commons.social.SocialAccountTwitterDetail" class="defaultDisplayHide"></div>
                <div id="facebookDetail" dojoType="encuestame.org.core.commons.social.SocialAccountFacebookDetail" class="defaultDisplayHide"></div>
                <div id="linkedinDetail" dojoType="encuestame.org.core.commons.social.SocialAccountLinkedInDetail" class="defaultDisplayHide"></div>
                <div id="googleDetail" dojoType="encuestame.org.core.commons.social.SocialAccountGoogleBuzzDetail" class="defaultDisplayHide"></div>
        </div>
    </div>

<div>
