<div class="socialAccounts">

    <div class="socialWrapper">
        <div class="listSocialCommunities">
                <div class="socialCommunitieItem">
                    TWITTER
                </div>
                <div class="socialCommunitieItem">
                    FACEBOOK
                </div>
                <div class="socialCommunitieItem">
                    LINKED IN
                </div>
        <div>

        <div class="socialAccountListDetail">


        </div>
    </div>

<div>
