package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CatState generated by hbm2java
 */
public class CatState implements java.io.Serializable {

	private Integer idState;
	private String descState;
	private String image;
	private Set<SurveySection> surveySections = new HashSet<SurveySection>(0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Questions> questionses = new HashSet<Questions>(0);

	public CatState() {
	}

	public CatState(String descState, String image,
			Set<SurveySection> surveySections, Set<Project> projects,
			Set<Questions> questionses) {
		this.descState = descState;
		this.image = image;
		this.surveySections = surveySections;
		this.projects = projects;
		this.questionses = questionses;
	}

	public Integer getIdState() {
		return this.idState;
	}

	public void setIdState(Integer idState) {
		this.idState = idState;
	}

	public String getDescState() {
		return this.descState;
	}

	public void setDescState(String descState) {
		this.descState = descState;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set<SurveySection> getSurveySections() {
		return this.surveySections;
	}

	public void setSurveySections(Set<SurveySection> surveySections) {
		this.surveySections = surveySections;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

}
