package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * ProjectUserId generated by hbm2java
 */
public class ProjectUserId implements java.io.Serializable {

	private int uid;
	private int proyectId;

	public ProjectUserId() {
	}

	public ProjectUserId(int uid, int proyectId) {
		this.uid = uid;
		this.proyectId = proyectId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(int proyectId) {
		this.proyectId = proyectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectUserId))
			return false;
		ProjectUserId castOther = (ProjectUserId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getProyectId() == castOther.getProyectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getProyectId();
		return result;
	}

}
