package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer proyectId;
	private CatState catState;
	private String description;
	private String info;
	private Date dateStart;
	private Date dateFinish;
	private Set<SurveyGroupProject> surveyGroupProjects = new HashSet<SurveyGroupProject>(
			0);
	private Set<ProjectLocation> projectLocations = new HashSet<ProjectLocation>(
			0);
	private Set<ProjectGroup> projectGroups = new HashSet<ProjectGroup>(0);
	private Set<ProjectUser> projectUsers = new HashSet<ProjectUser>(0);

	public Project() {
	}

	public Project(CatState catState, String description, String info,
			Date dateStart) {
		this.catState = catState;
		this.description = description;
		this.info = info;
		this.dateStart = dateStart;
	}

	public Project(CatState catState, String description, String info,
			Date dateStart, Date dateFinish,
			Set<SurveyGroupProject> surveyGroupProjects,
			Set<ProjectLocation> projectLocations,
			Set<ProjectGroup> projectGroups, Set<ProjectUser> projectUsers) {
		this.catState = catState;
		this.description = description;
		this.info = info;
		this.dateStart = dateStart;
		this.dateFinish = dateFinish;
		this.surveyGroupProjects = surveyGroupProjects;
		this.projectLocations = projectLocations;
		this.projectGroups = projectGroups;
		this.projectUsers = projectUsers;
	}

	public Integer getProyectId() {
		return this.proyectId;
	}

	public void setProyectId(Integer proyectId) {
		this.proyectId = proyectId;
	}

	public CatState getCatState() {
		return this.catState;
	}

	public void setCatState(CatState catState) {
		this.catState = catState;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public Date getDateFinish() {
		return this.dateFinish;
	}

	public void setDateFinish(Date dateFinish) {
		this.dateFinish = dateFinish;
	}

	public Set<SurveyGroupProject> getSurveyGroupProjects() {
		return this.surveyGroupProjects;
	}

	public void setSurveyGroupProjects(
			Set<SurveyGroupProject> surveyGroupProjects) {
		this.surveyGroupProjects = surveyGroupProjects;
	}

	public Set<ProjectLocation> getProjectLocations() {
		return this.projectLocations;
	}

	public void setProjectLocations(Set<ProjectLocation> projectLocations) {
		this.projectLocations = projectLocations;
	}

	public Set<ProjectGroup> getProjectGroups() {
		return this.projectGroups;
	}

	public void setProjectGroups(Set<ProjectGroup> projectGroups) {
		this.projectGroups = projectGroups;
	}

	public Set<ProjectUser> getProjectUsers() {
		return this.projectUsers;
	}

	public void setProjectUsers(Set<ProjectUser> projectUsers) {
		this.projectUsers = projectUsers;
	}

}
