package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * QuestionsRelations generated by hbm2java
 */
public class QuestionsRelations implements java.io.Serializable {

	private QuestionsRelationsId id;
	private QuestionColettion questionColettion;
	private Questions questions;
	private Date relationDate;

	public QuestionsRelations() {
	}

	public QuestionsRelations(QuestionsRelationsId id,
			QuestionColettion questionColettion, Questions questions,
			Date relationDate) {
		this.id = id;
		this.questionColettion = questionColettion;
		this.questions = questions;
		this.relationDate = relationDate;
	}

	public QuestionsRelationsId getId() {
		return this.id;
	}

	public void setId(QuestionsRelationsId id) {
		this.id = id;
	}

	public QuestionColettion getQuestionColettion() {
		return this.questionColettion;
	}

	public void setQuestionColettion(QuestionColettion questionColettion) {
		this.questionColettion = questionColettion;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	public Date getRelationDate() {
		return this.relationDate;
	}

	public void setRelationDate(Date relationDate) {
		this.relationDate = relationDate;
	}

}
