package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SurveyFormatGroup generated by hbm2java
 */
public class SurveyFormatGroup implements java.io.Serializable {

	private SurveyFormatGroupId id;
	private SurveyFormat surveyFormat;
	private SurveyGroup surveyGroup;
	private Boolean state;

	public SurveyFormatGroup() {
	}

	public SurveyFormatGroup(SurveyFormatGroupId id, SurveyFormat surveyFormat,
			SurveyGroup surveyGroup) {
		this.id = id;
		this.surveyFormat = surveyFormat;
		this.surveyGroup = surveyGroup;
	}

	public SurveyFormatGroup(SurveyFormatGroupId id, SurveyFormat surveyFormat,
			SurveyGroup surveyGroup, Boolean state) {
		this.id = id;
		this.surveyFormat = surveyFormat;
		this.surveyGroup = surveyGroup;
		this.state = state;
	}

	public SurveyFormatGroupId getId() {
		return this.id;
	}

	public void setId(SurveyFormatGroupId id) {
		this.id = id;
	}

	public SurveyFormat getSurveyFormat() {
		return this.surveyFormat;
	}

	public void setSurveyFormat(SurveyFormat surveyFormat) {
		this.surveyFormat = surveyFormat;
	}

	public SurveyGroup getSurveyGroup() {
		return this.surveyGroup;
	}

	public void setSurveyGroup(SurveyGroup surveyGroup) {
		this.surveyGroup = surveyGroup;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

}
