<div class="groupWidget">
     <div style="max-width: 160px; min-width: 150px;
     border: 1px solid #A29B9B; cursor: pointer;"  dojoAttachEvent="onclick:_onOpenMenu">
            <span style="color: #EEE;">Select Group</span>
    </div>
    <div class="defaultDisplayHide" style="background-color: #EEE; border: 1px solid #9A9A9A;
                position: absolute;min-width: 160px;" dojoAttachPoint="_items">
    </div>
</div>