<script src="<%=request.getContextPath()%>/resource/js/prototype.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/validation.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/scriptaculous.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/slider.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/effects.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/dragdrop.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/slider.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/builder.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/scriptaculous/controls.js" type="text/javascript"></script>
<script src="<%=request.getContextPath()%>/resource/js/encuestame-admon.js" type="text/javascript"></script>
