package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * CatLocationUserId generated by hbm2java
 */
public class CatLocationUserId implements java.io.Serializable {

	private int tid;
	private int siteid;
	private int uid;

	public CatLocationUserId() {
	}

	public CatLocationUserId(int tid, int siteid, int uid) {
		this.tid = tid;
		this.siteid = siteid;
		this.uid = uid;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatLocationUserId))
			return false;
		CatLocationUserId castOther = (CatLocationUserId) other;

		return (this.getTid() == castOther.getTid())
				&& (this.getSiteid() == castOther.getSiteid())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getSiteid();
		result = 37 * result + this.getUid();
		return result;
	}

}
