package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ProyectTypeSurveyId generated by hbm2java
 */
public class ProyectTypeSurveyId implements java.io.Serializable {

	private int siteid;
	private int stid;

	public ProyectTypeSurveyId() {
	}

	public ProyectTypeSurveyId(int siteid, int stid) {
		this.siteid = siteid;
		this.stid = stid;
	}

	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	public int getStid() {
		return this.stid;
	}

	public void setStid(int stid) {
		this.stid = stid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectTypeSurveyId))
			return false;
		ProyectTypeSurveyId castOther = (ProyectTypeSurveyId) other;

		return (this.getSiteid() == castOther.getSiteid())
				&& (this.getStid() == castOther.getStid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSiteid();
		result = 37 * result + this.getStid();
		return result;
	}

}
