package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ProyectTypeSurvey generated by hbm2java
 */
public class ProyectTypeSurvey implements java.io.Serializable {

	private ProyectTypeSurveyId id;

	public ProyectTypeSurvey() {
	}

	public ProyectTypeSurvey(ProyectTypeSurveyId id) {
		this.id = id;
	}

	public ProyectTypeSurveyId getId() {
		return this.id;
	}

	public void setId(ProyectTypeSurveyId id) {
		this.id = id;
	}

}
