package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ProyectGroup generated by hbm2java
 */
public class ProyectGroup implements java.io.Serializable {

	private ProyectGroupId id;
	private Date fechaIngreso;

	public ProyectGroup() {
	}

	public ProyectGroup(ProyectGroupId id, Date fechaIngreso) {
		this.id = id;
		this.fechaIngreso = fechaIngreso;
	}

	public ProyectGroupId getId() {
		return this.id;
	}

	public void setId(ProyectGroupId id) {
		this.id = id;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
