package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ProyectGroupId generated by hbm2java
 */
public class ProyectGroupId implements java.io.Serializable {

	private int groupId;
	private int siteid;

	public ProyectGroupId() {
	}

	public ProyectGroupId(int groupId, int siteid) {
		this.groupId = groupId;
		this.siteid = siteid;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectGroupId))
			return false;
		ProyectGroupId castOther = (ProyectGroupId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& (this.getSiteid() == castOther.getSiteid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getSiteid();
		return result;
	}

}
