package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ProyectUserId generated by hbm2java
 */
public class ProyectUserId implements java.io.Serializable {

	private int uid;
	private int siteid;

	public ProyectUserId() {
	}

	public ProyectUserId(int uid, int siteid) {
		this.uid = uid;
		this.siteid = siteid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getSiteid() {
		return this.siteid;
	}

	public void setSiteid(int siteid) {
		this.siteid = siteid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectUserId))
			return false;
		ProyectUserId castOther = (ProyectUserId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getSiteid() == castOther.getSiteid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getSiteid();
		return result;
	}

}
