package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * QuestionValidationType generated by hbm2java
 */
public class QuestionValidationType implements java.io.Serializable {

	private int idTypeVal;
	private String desVal;
	private String param;
	private String ayuda;
	private byte[] reglas;

	public QuestionValidationType() {
	}

	public QuestionValidationType(int idTypeVal) {
		this.idTypeVal = idTypeVal;
	}

	public QuestionValidationType(int idTypeVal, String desVal, String param,
			String ayuda, byte[] reglas) {
		this.idTypeVal = idTypeVal;
		this.desVal = desVal;
		this.param = param;
		this.ayuda = ayuda;
		this.reglas = reglas;
	}

	public int getIdTypeVal() {
		return this.idTypeVal;
	}

	public void setIdTypeVal(int idTypeVal) {
		this.idTypeVal = idTypeVal;
	}

	public String getDesVal() {
		return this.desVal;
	}

	public void setDesVal(String desVal) {
		this.desVal = desVal;
	}

	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	public String getAyuda() {
		return this.ayuda;
	}

	public void setAyuda(String ayuda) {
		this.ayuda = ayuda;
	}

	public byte[] getReglas() {
		return this.reglas;
	}

	public void setReglas(byte[] reglas) {
		this.reglas = reglas;
	}

}
