package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * QuestionsType generated by hbm2java
 */
public class QuestionsType implements java.io.Serializable {

	private Integer idQidType;
	private String desQid;
	private String labelQid;
	private String finalidad;

	public QuestionsType() {
	}

	public QuestionsType(String desQid, String labelQid, String finalidad) {
		this.desQid = desQid;
		this.labelQid = labelQid;
		this.finalidad = finalidad;
	}

	public Integer getIdQidType() {
		return this.idQidType;
	}

	public void setIdQidType(Integer idQidType) {
		this.idQidType = idQidType;
	}

	public String getDesQid() {
		return this.desQid;
	}

	public void setDesQid(String desQid) {
		this.desQid = desQid;
	}

	public String getLabelQid() {
		return this.labelQid;
	}

	public void setLabelQid(String labelQid) {
		this.labelQid = labelQid;
	}

	public String getFinalidad() {
		return this.finalidad;
	}

	public void setFinalidad(String finalidad) {
		this.finalidad = finalidad;
	}

}
