package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * ResultMod generated by hbm2java
 */
public class ResultMod implements java.io.Serializable {

	private Integer idMod;
	private int rid;
	private String previousResponse;
	private String newResponse;
	private Date modDate;
	private int uid;

	public ResultMod() {
	}

	public ResultMod(int rid, String previousResponse, Date modDate, int uid) {
		this.rid = rid;
		this.previousResponse = previousResponse;
		this.modDate = modDate;
		this.uid = uid;
	}

	public ResultMod(int rid, String previousResponse, String newResponse,
			Date modDate, int uid) {
		this.rid = rid;
		this.previousResponse = previousResponse;
		this.newResponse = newResponse;
		this.modDate = modDate;
		this.uid = uid;
	}

	public Integer getIdMod() {
		return this.idMod;
	}

	public void setIdMod(Integer idMod) {
		this.idMod = idMod;
	}

	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	public String getPreviousResponse() {
		return this.previousResponse;
	}

	public void setPreviousResponse(String previousResponse) {
		this.previousResponse = previousResponse;
	}

	public String getNewResponse() {
		return this.newResponse;
	}

	public void setNewResponse(String newResponse) {
		this.newResponse = newResponse;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

}
