package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ResultSurveyNivel1Id generated by hbm2java
 */
public class ResultSurveyNivel1Id implements java.io.Serializable {

	private long rid;
	private long ridN1;

	public ResultSurveyNivel1Id() {
	}

	public ResultSurveyNivel1Id(long rid, long ridN1) {
		this.rid = rid;
		this.ridN1 = ridN1;
	}

	public long getRid() {
		return this.rid;
	}

	public void setRid(long rid) {
		this.rid = rid;
	}

	public long getRidN1() {
		return this.ridN1;
	}

	public void setRidN1(long ridN1) {
		this.ridN1 = ridN1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResultSurveyNivel1Id))
			return false;
		ResultSurveyNivel1Id castOther = (ResultSurveyNivel1Id) other;

		return (this.getRid() == castOther.getRid())
				&& (this.getRidN1() == castOther.getRidN1());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRid();
		result = 37 * result + (int) this.getRidN1();
		return result;
	}

}
