package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * ResultSurveyNivel1 generated by hbm2java
 */
public class ResultSurveyNivel1 implements java.io.Serializable {

	private ResultSurveyNivel1Id id;
	private String label;
	private String respn1;

	public ResultSurveyNivel1() {
	}

	public ResultSurveyNivel1(ResultSurveyNivel1Id id, String label,
			String respn1) {
		this.id = id;
		this.label = label;
		this.respn1 = respn1;
	}

	public ResultSurveyNivel1Id getId() {
		return this.id;
	}

	public void setId(ResultSurveyNivel1Id id) {
		this.id = id;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getRespn1() {
		return this.respn1;
	}

	public void setRespn1(String respn1) {
		this.respn1 = respn1;
	}

}
