package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SecUsers generated by hbm2java
 */
public class SecUsers implements java.io.Serializable {

	private Integer uid;
	private String sex;
	private String name;
	private String email;
	private String username;
	private String password;
	private String passwordClean;
	private Integer birthDate;
	private String address;
	private String nocId;
	private int status;
	private String inviteCode;
	private int idState;
	private String position;
	private Date dateNew;
	private String publisher;
	private Set<SecGroupUser> secGroupUsers = new HashSet<SecGroupUser>(0);

	public SecUsers() {
	}

	public SecUsers(String name, String email, String password, int status,
			int idState, Date dateNew, String publisher) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.status = status;
		this.idState = idState;
		this.dateNew = dateNew;
		this.publisher = publisher;
	}

	public SecUsers(String sex, String name, String email, String username,
			String password, String passwordClean, Integer birthDate,
			String address, String nocId, int status, String inviteCode,
			int idState, String position, Date dateNew, String publisher,
			Set<SecGroupUser> secGroupUsers) {
		this.sex = sex;
		this.name = name;
		this.email = email;
		this.username = username;
		this.password = password;
		this.passwordClean = passwordClean;
		this.birthDate = birthDate;
		this.address = address;
		this.nocId = nocId;
		this.status = status;
		this.inviteCode = inviteCode;
		this.idState = idState;
		this.position = position;
		this.dateNew = dateNew;
		this.publisher = publisher;
		this.secGroupUsers = secGroupUsers;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordClean() {
		return this.passwordClean;
	}

	public void setPasswordClean(String passwordClean) {
		this.passwordClean = passwordClean;
	}

	public Integer getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Integer birthDate) {
		this.birthDate = birthDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNocId() {
		return this.nocId;
	}

	public void setNocId(String nocId) {
		this.nocId = nocId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getInviteCode() {
		return this.inviteCode;
	}

	public void setInviteCode(String inviteCode) {
		this.inviteCode = inviteCode;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Date getDateNew() {
		return this.dateNew;
	}

	public void setDateNew(Date dateNew) {
		this.dateNew = dateNew;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Set<SecGroupUser> getSecGroupUsers() {
		return this.secGroupUsers;
	}

	public void setSecGroupUsers(Set<SecGroupUser> secGroupUsers) {
		this.secGroupUsers = secGroupUsers;
	}

}
