package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SecUsersInstId generated by hbm2java
 */
public class SecUsersInstId implements java.io.Serializable {

	private int uid;
	private int instId;

	public SecUsersInstId() {
	}

	public SecUsersInstId(int uid, int instId) {
		this.uid = uid;
		this.instId = instId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getInstId() {
		return this.instId;
	}

	public void setInstId(int instId) {
		this.instId = instId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecUsersInstId))
			return false;
		SecUsersInstId castOther = (SecUsersInstId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getInstId() == castOther.getInstId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUid();
		result = 37 * result + this.getInstId();
		return result;
	}

}
