package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SecUsersInst generated by hbm2java
 */
public class SecUsersInst implements java.io.Serializable {

	private SecUsersInstId id;

	public SecUsersInst() {
	}

	public SecUsersInst(SecUsersInstId id) {
		this.id = id;
	}

	public SecUsersInstId getId() {
		return this.id;
	}

	public void setId(SecUsersInstId id) {
		this.id = id;
	}

}
