package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SurveyTimeId generated by hbm2java
 */
public class SurveyTimeId implements java.io.Serializable {

	private int sequence;
	private int sid;

	public SurveyTimeId() {
	}

	public SurveyTimeId(int sequence, int sid) {
		this.sequence = sequence;
		this.sid = sid;
	}

	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SurveyTimeId))
			return false;
		SurveyTimeId castOther = (SurveyTimeId) other;

		return (this.getSequence() == castOther.getSequence())
				&& (this.getSid() == castOther.getSid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSequence();
		result = 37 * result + this.getSid();
		return result;
	}

}
