package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SurveyQuestionDependency generated by hbm2java
 */
public class SurveyQuestionDependency implements java.io.Serializable {

	private SurveyQuestionDependencyId id;
	private String patronData;
	private float patronLimit;
	private Float depHome;
	private String patronOption;
	private Integer qidLim;
	private int idState;

	public SurveyQuestionDependency() {
	}

	public SurveyQuestionDependency(SurveyQuestionDependencyId id,
			String patronData, float patronLimit, String patronOption,
			int idState) {
		this.id = id;
		this.patronData = patronData;
		this.patronLimit = patronLimit;
		this.patronOption = patronOption;
		this.idState = idState;
	}

	public SurveyQuestionDependency(SurveyQuestionDependencyId id,
			String patronData, float patronLimit, Float depHome,
			String patronOption, Integer qidLim, int idState) {
		this.id = id;
		this.patronData = patronData;
		this.patronLimit = patronLimit;
		this.depHome = depHome;
		this.patronOption = patronOption;
		this.qidLim = qidLim;
		this.idState = idState;
	}

	public SurveyQuestionDependencyId getId() {
		return this.id;
	}

	public void setId(SurveyQuestionDependencyId id) {
		this.id = id;
	}

	public String getPatronData() {
		return this.patronData;
	}

	public void setPatronData(String patronData) {
		this.patronData = patronData;
	}

	public float getPatronLimit() {
		return this.patronLimit;
	}

	public void setPatronLimit(float patronLimit) {
		this.patronLimit = patronLimit;
	}

	public Float getDepHome() {
		return this.depHome;
	}

	public void setDepHome(Float depHome) {
		this.depHome = depHome;
	}

	public String getPatronOption() {
		return this.patronOption;
	}

	public void setPatronOption(String patronOption) {
		this.patronOption = patronOption;
	}

	public Integer getQidLim() {
		return this.qidLim;
	}

	public void setQidLim(Integer qidLim) {
		this.qidLim = qidLim;
	}

	public int getIdState() {
		return this.idState;
	}

	public void setIdState(int idState) {
		this.idState = idState;
	}

}
