package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SurveyDetalle generated by hbm2java
 */
public class SurveyDetalle implements java.io.Serializable {

	private SurveyDetalleId id;
	private Integer posicion;
	private float nopreg;
	private String template;
	private Integer idPatron;

	public SurveyDetalle() {
	}

	public SurveyDetalle(SurveyDetalleId id, float nopreg) {
		this.id = id;
		this.nopreg = nopreg;
	}

	public SurveyDetalle(SurveyDetalleId id, Integer posicion, float nopreg,
			String template, Integer idPatron) {
		this.id = id;
		this.posicion = posicion;
		this.nopreg = nopreg;
		this.template = template;
		this.idPatron = idPatron;
	}

	public SurveyDetalleId getId() {
		return this.id;
	}

	public void setId(SurveyDetalleId id) {
		this.id = id;
	}

	public Integer getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Integer posicion) {
		this.posicion = posicion;
	}

	public float getNopreg() {
		return this.nopreg;
	}

	public void setNopreg(float nopreg) {
		this.nopreg = nopreg;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public Integer getIdPatron() {
		return this.idPatron;
	}

	public void setIdPatron(Integer idPatron) {
		this.idPatron = idPatron;
	}

}
