package org.jp.developer.persistence.pojo;

// Generated 01-17-2009 11:50:28 AM by Hibernate Tools 3.2.2.GA

/**
 * SurveySectionType generated by hbm2java
 */
public class SurveySectionType implements java.io.Serializable {

	private SurveySectionTypeId id;

	public SurveySectionType() {
	}

	public SurveySectionType(SurveySectionTypeId id) {
		this.id = id;
	}

	public SurveySectionTypeId getId() {
		return this.id;
	}

	public void setId(SurveySectionTypeId id) {
		this.id = id;
	}

}
