<%@ include file="/WEB-INF/jsp/includes/taglibs.jsp"%>
<c:if test="${!development}">
    <!-- File generated by dojo build-->
    <script src="<%=request.getContextPath()%>/resources/js/me/web/widget/stream/FrontEnd.js"></script>
</c:if>

