<div style="padding: 10px;">
<div dojoType="dijit.form.Form" id="tableForm">
    <table cellpadding="5" cellspacing="4">
        <tbody dojoAttachPoint="_body">
            <tr>
                <th>Select</th>
                <th>Name</th>
                <th>Email</th>
                <th>Permissions</th>
                <th>User from</th>
                <th>Status</th>
                <th>Options</th>
            </tr>
        </tbody>
    </table>
    <div class="controlsTable" style="cursor: pointer;">
        <a dojoAttachEvent="onclick:first"> First Page</a>
        <a dojoAttachEvent="onclick:previous"> Previous </a>
        <a dojoAttachEvent="onclick:next">Next > </a>
        <a dojoAttachEvent="onclick:last">Last Page  </a>
    </div>
</div>
</div>