package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * CatLocationUserId generated by hbm2java
 */
public class CatLocationUserId implements java.io.Serializable {

	private int locationId;
	private int uid;

	public CatLocationUserId() {
	}

	public CatLocationUserId(int locationId, int uid) {
		this.locationId = locationId;
		this.uid = uid;
	}

	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatLocationUserId))
			return false;
		CatLocationUserId castOther = (CatLocationUserId) other;

		return (this.getLocationId() == castOther.getLocationId())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLocationId();
		result = 37 * result + this.getUid();
		return result;
	}

}
