package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SecGroupUserId generated by hbm2java
 */
public class SecGroupUserId implements java.io.Serializable {

	private int groupId;
	private int uid;

	public SecGroupUserId() {
	}

	public SecGroupUserId(int groupId, int uid) {
		this.groupId = groupId;
		this.uid = uid;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecGroupUserId))
			return false;
		SecGroupUserId castOther = (SecGroupUserId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getUid();
		return result;
	}

}
