package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

/**
 * SurveyFormatGroupId generated by hbm2java
 */
public class SurveyFormatGroupId implements java.io.Serializable {

	private int sgId;
	private int idSidFormat;

	public SurveyFormatGroupId() {
	}

	public SurveyFormatGroupId(int sgId, int idSidFormat) {
		this.sgId = sgId;
		this.idSidFormat = idSidFormat;
	}

	public int getSgId() {
		return this.sgId;
	}

	public void setSgId(int sgId) {
		this.sgId = sgId;
	}

	public int getIdSidFormat() {
		return this.idSidFormat;
	}

	public void setIdSidFormat(int idSidFormat) {
		this.idSidFormat = idSidFormat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SurveyFormatGroupId))
			return false;
		SurveyFormatGroupId castOther = (SurveyFormatGroupId) other;

		return (this.getSgId() == castOther.getSgId())
				&& (this.getIdSidFormat() == castOther.getIdSidFormat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSgId();
		result = 37 * result + this.getIdSidFormat();
		return result;
	}

}
