package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SurveyResult generated by hbm2java
 */
public class SurveyResult implements java.io.Serializable {

	private Long rid;
	private int qid;
	private long sid;
	private String resp;
	private Set<SurveyResultMod> surveyResultMods = new HashSet<SurveyResultMod>(
			0);

	public SurveyResult() {
	}

	public SurveyResult(int qid, long sid, String resp) {
		this.qid = qid;
		this.sid = sid;
		this.resp = resp;
	}

	public SurveyResult(int qid, long sid, String resp,
			Set<SurveyResultMod> surveyResultMods) {
		this.qid = qid;
		this.sid = sid;
		this.resp = resp;
		this.surveyResultMods = surveyResultMods;
	}

	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public long getSid() {
		return this.sid;
	}

	public void setSid(long sid) {
		this.sid = sid;
	}

	public String getResp() {
		return this.resp;
	}

	public void setResp(String resp) {
		this.resp = resp;
	}

	public Set<SurveyResultMod> getSurveyResultMods() {
		return this.surveyResultMods;
	}

	public void setSurveyResultMods(Set<SurveyResultMod> surveyResultMods) {
		this.surveyResultMods = surveyResultMods;
	}

}
