package org.encuestame.core.persistence.pojo;

// Generated 29-may-2009 13:17:50 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SurveyFormat generated by hbm2java
 */
public class SurveyFormat implements java.io.Serializable {

	private int idSidFormat;
	private String name;
	private Date dateCreated;
	private Set<SurveyFormatGroup> surveyFormatGroups = new HashSet<SurveyFormatGroup>(
			0);
	private Set<SurveyDetail> surveyDetails = new HashSet<SurveyDetail>(0);

	public SurveyFormat() {
	}

	public SurveyFormat(int idSidFormat) {
		this.idSidFormat = idSidFormat;
	}

	public SurveyFormat(int idSidFormat, String name, Date dateCreated,
			Set<SurveyFormatGroup> surveyFormatGroups,
			Set<SurveyDetail> surveyDetails) {
		this.idSidFormat = idSidFormat;
		this.name = name;
		this.dateCreated = dateCreated;
		this.surveyFormatGroups = surveyFormatGroups;
		this.surveyDetails = surveyDetails;
	}

	public int getIdSidFormat() {
		return this.idSidFormat;
	}

	public void setIdSidFormat(int idSidFormat) {
		this.idSidFormat = idSidFormat;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Set<SurveyFormatGroup> getSurveyFormatGroups() {
		return this.surveyFormatGroups;
	}

	public void setSurveyFormatGroups(Set<SurveyFormatGroup> surveyFormatGroups) {
		this.surveyFormatGroups = surveyFormatGroups;
	}

	public Set<SurveyDetail> getSurveyDetails() {
		return this.surveyDetails;
	}

	public void setSurveyDetails(Set<SurveyDetail> surveyDetails) {
		this.surveyDetails = surveyDetails;
	}

}
